ministryofjustice/hmpps-activities-management

server/views/pages/index.njk

Activity list spike

---

server/@types/activities.ts
server/@types/activitiesAPI/types.ts
server/data/activitiesApiClient.test.ts
server/data/activitiesApiClient.ts
server/routes/activity-list-am/handlers/activityListHelper.ts
server/services/activitiesService.ts

fetch attendance info from activities management api for rolled out prisons

SAA-130 Minimal activity list migration - fetch attendance info

---

server/@types/activitiesAPI/index.d.ts
server/services/activitiesService.test.ts
server/services/fixtures/activity_schedules_1.json

Minor changes to cater for recent API type alterations.
(suspensions, days of the week, incentiveLevel, payBand)

SAA-172: Updated API types and fixed tests affected.

---

helm_deploy/hmpps-activities-management/values.yaml

Updating the helm config to use the latest ingress for the UI.

SAA-187 switching to latest ingress controller v1.2 as required by cloud platform.

---

server/@types/activitiesAPI/index.d.ts

**DO NOT MERGE UNTIL API CHANGE IS MERGED**
Activity API updates in line with this [PR](https://github.com/ministryofjustice/hmpps-activities-management-api/pull/84) on the API

SAA-98 updating the activites api types inline with changes to the API.

---

server/app.ts
server/commonValidationTypes/simpleDate.test.ts
server/commonValidationTypes/simpleDate.ts
server/middleware/timeNowMiddleware.test.ts
server/middleware/timeNowMiddleware.ts
server/middleware/validationMiddleware.test.ts
server/middleware/validationMiddleware.ts
server/routes/allocate-to-activity/index.ts
server/routes/change-location/index.ts
server/routes/index.ts
server/routes/record-attendance/handlers/selectPeriod.test.ts
server/routes/record-attendance/handlers/selectPeriod.ts
server/routes/record-attendance/index.ts
server/routes/spikes/index.ts
server/utils/utils.ts
server/validators/isValidDate.test.ts
server/validators/isValidDate.ts
server/views/components/datePicker.njk
server/views/components/datePicker.test.ts
server/views/layout.njk
server/views/pages/home/index.njk
server/views/pages/record-attendance/select-period.njk

SAA-228: Attendance list - Select activity period route

---

docker-compose.yml
server/views/pages/allocate-to-activity/candidates/identify-candidates/macros/alertFlags.njk
server/views/pages/allocate-to-activity/candidates/identify-candidates/macros/candidateActivityInfo.njk
server/views/tabsLayout.njk

Some of the peer review suggestions

Saa 212 identify candidates peer review

---

server/routes/allocate-to-activity/candidates/identify-candidates/handlers/IdentifyCandidatesRouteHandler.test.ts
server/routes/allocate-to-activity/candidates/identify-candidates/handlers/IdentifyCandidatesRouteHandler.ts
server/views/pages/allocate-to-activity/candidates/identify-candidates/index.njk

Reinstating sort functionality lost in integration refactor

SAA-212 Identify candidates

---

integration_tests/fixtures/activitiesApi/getActivity.json
integration_tests/fixtures/activitiesApi/getCategories.json
integration_tests/fixtures/activitiesApi/getSchedule.json
integration_tests/fixtures/activitiesApi/getSchedulesInActivity.json
server/@types/activitiesAPI/index.d.ts
server/routes/allocate-to-activity/handlers/categories.test.ts
server/services/fixtures/activity_schedule_1.json
server/services/fixtures/activity_schedule_2.json
server/services/fixtures/activity_schedules_1.json
server/views/pages/allocate-to-activity/categories-dashboard.njk

SAA-258 ActivityCategory

---

generate-activities-types.sh
server/@types/activities.ts
server/@types/activitiesAPI/index.d.ts
server/services/activitiesService.ts
server/services/fixtures/activity_schedule_1.json
server/services/fixtures/activity_schedule_2.json
server/services/fixtures/activity_schedule_allocation_1.json
server/services/fixtures/activity_schedules_1.json
server/views/pages/allocate-to-activity/schedule.njk

Updated types and test json to match DM changes
Updated allocation schedule tab to match DM

SAA-273 DM Changes for slots

---

server/data/activitiesApiClient.ts
server/errorHandler.test.ts
server/errorHandler.ts

Change call to update attendances to use system token Tweaked error handler to show error for 403. Problem with error handling needs further work - redirects from this middleware do not work

SAA-281 Roles

---

server/data/activitiesApiClient.test.ts
server/data/activitiesApiClient.ts
server/routes/index.ts
server/routes/manage-schedules/handlers/activities.test.ts
server/routes/manage-schedules/handlers/activities.ts
server/routes/manage-schedules/index.ts
server/services/activitiesService.test.ts
server/services/activitiesService.ts
server/views/pages/home/index.njk
server/views/pages/manage-schedules/activities-dashboard.njk

New card on home page and new activities dashboard page for manage schedules journey

SAA-279 Basic activities dashboard

---

helm_deploy/hmpps-activities-management/values.yaml
server/views/pages/unlock-list/planned-events.njk

* Removes an unused but still imported template
* Adds Gerry IP to allowlist

SAA-256: Unused template removal 

---

integration_tests/e2e/appointments/createSingleAppointmentBackLinks.cy.ts
integration_tests/pages/appointments/createSingle/categoryPage.ts
integration_tests/pages/appointments/createSingle/locationPage.ts
integration_tests/pages/appointments/createSingle/selectPrisonerPage.ts
integration_tests/pages/page.ts

Added end to end tests covering:
- Back links from each page
- Changing answers

SAA-348: Additional end to end tests for create appointments journey

---

server/routes/spikes/handlers/calendarSpike.ts
server/routes/spikes/index.ts
server/views/pages/home/index.njk
server/views/pages/spikes/calendarSpikePrisonerSearch.njk

**New Page**
**New Page with Error**

SAA-382 - Added page to enter the prisoner number of the calendar to view

---

integration_tests/e2e/allocateToActivity.cy.ts
integration_tests/pages/allocateToActivity/AllocationDashboard.ts
server/routes/allocate-to-activity/handlers/allocationDashboard.test.ts
server/routes/allocate-to-activity/handlers/allocationDashboard.ts
server/views/pages/allocate-to-activity/allocation-dashboard.njk

Added search input to allocation dashboard to query candidates.
- Added search bar to allocation dashboard
- Added candidate search logic to allocation handler
- Included candidate search step to allocation e2e test

SAA-344: Allocate to activity - prisoner search

---

server/middleware/successMessageMiddleware.test.ts
server/middleware/successMessageMiddleware.ts
server/routes/create-an-activity/handlers/removePay.test.ts
server/routes/create-an-activity/handlers/removePay.ts
server/routes/create-an-activity/index.ts
server/routes/index.ts
server/views/pages/create-an-activity/check-pay.njk
server/views/pages/create-an-activity/remove-pay.njk

Added confirmation page for removal of pay bands

SAA-364: Remove pay confirmation page

---

server/routes/unlock-list/handlers/plannedEvents.ts
server/services/unlockListService.test.ts
server/services/unlockListService.ts
server/views/pages/unlock-list/planned-events.njk

* Fixed - table sort using both sub location and cell
* Implemented initial filter for staying or leaving the wing
* Added more tests for filters

SAA-371 unlock filtering and tests

---

server/routes/create-an-activity/handlers/removePay.test.ts
server/routes/create-an-activity/handlers/removePay.ts
server/views/pages/create-an-activity/check-pay.njk

Switches panel component to notification-banner for remove pay success message.

SAA-364: Updated success component

---

frontend/utilities/_typography.scss
integration_tests/components/datePicker.ts
integration_tests/components/summaryList.ts
integration_tests/e2e/createSchedule.cy.ts
integration_tests/fixtures/activitiesApi/getActivity.json
integration_tests/fixtures/prisonApi/getEventLocations.json
integration_tests/pages/createSchedule/bankHoliday.ts
integration_tests/pages/createSchedule/capacity.ts
integration_tests/pages/createSchedule/checkAnswers.ts
integration_tests/pages/createSchedule/confirmation.ts
integration_tests/pages/createSchedule/daysAndTimes.ts
integration_tests/pages/createSchedule/endDate.ts
integration_tests/pages/createSchedule/endDateOption.ts
integration_tests/pages/createSchedule/location.ts
integration_tests/pages/createSchedule/name.ts
integration_tests/pages/createSchedule/startDate.ts
integration_tests/pages/page.ts
server/routes/manage-schedules/create-schedule/handlers/checkAnswers.test.ts
server/routes/manage-schedules/create-schedule/handlers/checkAnswers.ts
server/views/components/activitySummary.njk
server/views/components/scheduleSummary.njk
server/views/pages/allocate-to-activity/check-answers.njk
server/views/pages/appointments/create-single/check-answers.njk
server/views/pages/create-an-activity/check-answers.njk
server/views/pages/manage-schedules/create-schedule/capacity.njk
server/views/pages/manage-schedules/create-schedule/check-answers.njk
server/views/pages/manage-schedules/create-schedule/confirmation.njk
server/views/pages/manage-schedules/create-schedule/days-and-times.njk

Added E2E test for create schedule journey.
**Note:** PR also includes minor changes to check answers page to bring more inline with prototype.

SAA-376: Create schedule journey E2E test

---

integration_tests/e2e/recordAttendance.cy.ts
integration_tests/fixtures/activitiesApi/getScheduledInstance-cancelled.json
integration_tests/pages/page.ts
integration_tests/pages/recordAttendance/attendanceList.ts
integration_tests/pages/recordAttendance/cancelSessionConfirm.ts
integration_tests/pages/recordAttendance/cancelSessionReason.ts
integration_tests/pages/recordAttendance/uncancelSessionConfirm.ts
server/routes/record-attendance/handlers/attendanceList.test.ts
server/routes/record-attendance/handlers/attendanceList.ts
server/views/fixtures/pages/record-attendance/attendance-list-cancelled.json
server/views/fixtures/pages/record-attendance/attendance-list.json
server/views/pages/record-attendance/attendance-list.njk
server/views/pages/record-attendance/attendance-list.njk.test.ts
server/views/pages/record-attendance/cancel-session/cancel-reason.njk
server/views/pages/record-attendance/cancel-session/confirm.njk
server/views/pages/record-attendance/uncancel-session/confirm.njk

- Added e2e tests for cancel / uncancel session journeys
- Added cheerio tests for attendance-list template

SAA-481: Cancel session e2e tests

---

integration_tests/pages/recordAttendance/attendanceList.ts
server/nunjucks/nunjucksSetup.ts
server/utils/utils.ts
server/views/components/multi-select.njk
server/views/pages/record-attendance/attendance-list.njk

Removes multi-select when not needed to fix UI bug, https://dsdmoj.atlassian.net/browse/SAA-519

SAA-519: Remove multiselect if not needed

---

server/views/partials/showUnlockEvents.njk

Fix for appointment types not showing.

SAA-570: Typo in nunjucks - not recognising SAA appointments

---

assets/downloads/prisoner-list.csv
integration_tests/e2e/appointments/createGroupAppointment.cy.ts
integration_tests/e2e/appointments/createGroupAppointmentCsvUploadValidation.cy.ts
integration_tests/e2e/appointments/createGroupRepeatAppointment.cy.ts
integration_tests/pages/appointments/create-and-edit/uploadbyCsvPage.ts
integration_tests/pages/page.ts
server/routes/appointments/create-and-edit/createRoutes.ts
server/routes/appointments/create-and-edit/handlers/howToAddPrisoners.test.ts
server/routes/appointments/create-and-edit/handlers/howToAddPrisoners.ts
server/routes/appointments/create-and-edit/handlers/uploadByCsv.test.ts
server/routes/appointments/create-and-edit/handlers/uploadByCsv.ts
server/routes/appointments/index.ts
server/views/pages/appointments/create-and-edit/upload-by-csv.njk

Adds new "upload by CSV" page to the create group appointment journey

SAA-577: Added upload by CSV page

---

server/views/pages/appointments/create-and-edit/category.njk
server/views/pages/appointments/create-and-edit/check-answers.njk
server/views/pages/appointments/create-and-edit/confirmation.njk
server/views/pages/appointments/create-and-edit/date-and-time.njk
server/views/pages/appointments/create-and-edit/description.njk
server/views/pages/appointments/create-and-edit/how-to-add-prisoners.njk
server/views/pages/appointments/create-and-edit/location.njk
server/views/pages/appointments/create-and-edit/repeat-period-and-count.njk
server/views/pages/appointments/create-and-edit/repeat.njk
server/views/pages/appointments/create-and-edit/review-prisoners.njk
server/views/pages/appointments/create-and-edit/select-prisoner.njk
server/views/pages/appointments/create-and-edit/upload-prisoner-list.njk
server/views/pages/appointments/partials/appointment-journey-title.njk

Updates appointment journey page titles to be relevant to the journey mode & type.

SAA-599: Updated appointment journey titles

---

integration_tests/mockApis/prisonApi.ts
package-lock.json
package.json
server/config.ts
server/middleware/routeAuthMiddleware.test.ts
server/middleware/routeAuthMiddleware.ts
server/routes/index.ts

- Added middleware to check user roles against the current route
- Displays an error message when the user doesn't have the necessary roles to access the route
- Added global config where routes and their roles can be defined

SAA-306: Added middleware to auth routes by user role

---

server/views/pages/appointments/create-and-edit/check-answers.njk

Tiny fix for bulk appointment change link

SAA-604: Fixed date change link

---

server/routes/record-attendance/handlers/attendanceList.ts
server/services/unlockListService.ts

We were seeing logs to indicate prisoner search was being called with no prisoners.
A few checks and I could see 2 or 3 places where this might happen.
This PR has minor changes to check and avoid calling if there's no point.

SAA-626 check search with no prisoners

---

server/@types/activitiesAPI/index.d.ts
server/routes/create-an-activity/handlers/endDate.test.ts
server/routes/create-an-activity/handlers/endDate.ts
server/routes/create-an-activity/handlers/location.ts
server/routes/manage-schedules/handlers/activities.test.ts
server/routes/manage-schedules/handlers/activities.ts
server/views/pages/home/index.njk
server/views/pages/manage-schedules/activities-dashboard.njk

SAA-477: Update activities dashboard

---

.circleci/config.yml
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
server/config.ts

Enabling the preprod environment (UI).

SAA-609: Adding preprod circle and helm values.

---

server/@types/appointments.ts
server/data/activitiesApiClient.test.ts
server/nunjucks/nunjucksSetup.ts
server/routes/appointments/create-and-edit/createRoutes.ts
server/routes/appointments/create-and-edit/editAppointmentJourney.ts
server/routes/appointments/create-and-edit/editRoutes.ts
server/routes/appointments/create-and-edit/handlers/applyTo.ts
server/routes/appointments/create-and-edit/handlers/cancellationReason.ts
server/routes/appointments/create-and-edit/handlers/comment.ts
server/routes/appointments/create-and-edit/handlers/dateAndTime.ts
server/routes/appointments/create-and-edit/handlers/location.ts
server/routes/appointments/create-and-edit/handlers/reviewPrisoners.test.ts
server/routes/appointments/create-and-edit/handlers/reviewPrisoners.ts
server/routes/appointments/create-and-edit/handlers/startJourney.test.ts
server/routes/appointments/create-and-edit/handlers/startJourney.ts
server/services/activitiesService.test.ts
server/services/editAppointmentService.test.ts
server/services/editAppointmentService.ts
server/utils/editAppointmentUtils.test.ts
server/utils/editAppointmentUtils.ts
server/views/pages/appointments/create-and-edit/apply-to.njk

Moved view focused logic to new utils file

SAA-738: Fix for incorrect apply to options when appointment has been deleted

---

server/routes/unlock-list/handlers/selectDateAndLocation.test.ts
server/routes/unlock-list/handlers/selectDateAndLocation.ts
server/views/pages/unlock-list/select-date-and-location.njk

Minor content changes to the unlock list form

SAA-621: Unlock list content updates

---

server/routes/record-attendance/handlers/attendanceDetails.test.ts
server/routes/record-attendance/handlers/attendanceDetails.ts
server/views/pages/record-attendance/attendance-details.njk

Minor content tweaks to the attendance details page

SAA-723: Attendance details content updates

---

server/routes/record-attendance/handlers/activities.test.ts
server/routes/record-attendance/handlers/activities.ts
server/routes/unlock-list/handlers/selectDateAndLocation.test.ts
server/routes/unlock-list/handlers/selectDateAndLocation.ts
server/views/pages/record-attendance/activities.njk
server/views/pages/record-attendance/select-period.njk
server/views/pages/unlock-list/select-date-and-location.njk

Minor content updates to record attendance pages

SAA-627 & SAA-628: Content updates

---

server/views/components/multi-select.njk
server/views/pages/record-attendance/attendance-list.njk

Minor content changes to the attendance list page

SAA-629 & SAA-633: Minor content changes

---

server/@types/activitiesAPI/index.d.ts
server/views/pages/allocation-dashboard/allocation-dashboard.njk

This is related to [API PR](https://github.com/ministryofjustice/hmpps-activities-management-api/pull/362)

SAA-780 the reason codes presented to the UI need to be restricted to a subset of codes.

---

server/nunjucks/nunjucksSetup.ts
server/utils/utils.ts
server/views/pages/appointments/create-and-edit/description.njk
server/views/pages/create-an-activity/name.njk
server/views/partials/characterCountInput.njk

Addition of character count to activity name input and page heading update

SAA-774: Activity name content changes

---

server/views/pages/unlock-list/select-date-and-location.njk

SAA-621: Unlock list form activity slot

---

server/@types/activitiesAPI/index.d.ts
server/@types/activitiesAPI/types.ts
server/data/activitiesApiClient.test.ts
server/data/activitiesApiClient.ts
server/enum/attendanceStatus.ts
server/routes/change-of-circumstances/handlers/changeOfCircumstanceRoutes.ts
server/routes/change-of-circumstances/handlers/changeOfCircumstancesRoutes.test.ts
server/services/activitiesService.test.ts
server/services/activitiesService.ts
server/utils/utils.test.ts
server/utils/utils.ts

This PR:
* Implements the POST route in the change events handler to acknowledge changes of circumstances in the prison.
* Adds tests for these routes, service calls and API client calls.
* Removes LOCKED as a valid attendance status.
* Updates the API client types to match the API as it stands now.
* Removes some default pagination, now that the API has this data.

SAA-777: Acknowledging change events.

---

integration_tests/e2e/allocateToActivity.cy.ts
integration_tests/fixtures/activitiesApi/getCandidateSuitability.json
integration_tests/pages/allocateToActivity/before-you-allocate.ts
server/@types/activitiesAPI/index.d.ts
server/@types/activitiesAPI/types.ts
server/data/activitiesApiClient.test.ts
server/data/activitiesApiClient.ts
server/routes/allocate-to-activity/handlers/beforeYouAllocate.test.ts
server/routes/allocate-to-activity/handlers/beforeYouAllocate.ts
server/routes/allocate-to-activity/handlers/startJourney.test.ts
server/routes/allocate-to-activity/handlers/startJourney.ts
server/routes/allocate-to-activity/index.ts
server/routes/allocation-dashboard/handlers/checkAllocation.test.ts
server/routes/allocation-dashboard/handlers/checkAllocation.ts
server/routes/allocation-dashboard/handlers/endDate.test.ts
server/routes/allocation-dashboard/handlers/endDateOption.test.ts
server/routes/allocation-dashboard/handlers/payBand.test.ts
server/routes/allocation-dashboard/handlers/payBand.ts
server/routes/allocation-dashboard/handlers/startDate.test.ts
server/routes/manage-schedules/handlers/helpers/incentiveLevelPayMappingUtil.ts
server/services/activitiesService.test.ts
server/services/activitiesService.ts
server/views/pages/allocate-to-activity/before-you-allocate.njk

Adds the "before you allocate" page to the allocation journey

SAA-669: Before you allocate

---

server/routes/create-an-activity/handlers/bankHoliday.ts
server/routes/create-an-activity/handlers/category.test.ts
server/routes/create-an-activity/handlers/category.ts
server/routes/create-an-activity/journey.ts
server/views/pages/create-an-activity/capacity.njk

Defaults location of "not in work" activities to "in cell" and skips the location step of the create activity journey

SAA-493: Default not in work location

---

server/@types/activitiesAPI/index.d.ts
server/routes/allocate-to-activity/handlers/beforeYouAllocate.test.ts
server/routes/allocate-to-activity/handlers/beforeYouAllocate.ts
server/routes/allocation-dashboard/handlers/checkAllocation.test.ts
server/routes/allocation-dashboard/handlers/checkAllocation.ts
server/routes/allocation-dashboard/handlers/endDate.test.ts
server/routes/allocation-dashboard/handlers/endDateOption.test.ts
server/routes/allocation-dashboard/handlers/payBand.test.ts
server/routes/allocation-dashboard/handlers/payBand.ts
server/routes/allocation-dashboard/handlers/startDate.test.ts
server/routes/manage-schedules/handlers/helpers/incentiveLevelPayMappingUtil.ts
server/views/pages/allocate-to-activity/before-you-allocate.njk

UI updates for API model changes, https://github.com/ministryofjustice/hmpps-activities-management-api/pull/413

SAA-871: UI changes for Allocation + AllocationSuitability model updates

---

server/routes/appointments/search/handlers/select-date.test.ts
server/routes/appointments/search/handlers/select-date.ts
server/routes/appointments/search/index.ts
server/views/pages/appointments/home/index.njk
server/views/pages/appointments/search/results.njk
server/views/pages/appointments/search/results.njk.test.ts
server/views/pages/appointments/search/select-date.njk

Adds select date page for viewing appointments and a minor content update to appointment dashboard

SAA-879: Added view appointments select date page

---

server/views/pages/activities/create-an-activity/risk-level.njk

Minor updates to workplace risk assessment page

SAA-771: Content fixes

---

server/@types/activitiesAPI/index.d.ts
server/routes/activities/create-an-activity/handlers/checkAnswers.ts
server/routes/activities/create-an-activity/handlers/location.test.ts
server/routes/activities/create-an-activity/handlers/location.ts
server/routes/activities/create-an-activity/journey.ts
server/routes/activities/manage-schedules/handlers/activity.ts
server/views/pages/activities/create-an-activity/check-answers.njk
server/views/pages/activities/create-an-activity/location.njk
server/views/pages/activities/manage-schedules/view-activity.njk
server/views/partials/showUnlockEvents.njk

- Adds "On wing" location option to create / edit journey
- Adds support for "On wing" location on pages that display activity location

SAA-935: On wing activity location

---

integration_tests/e2e/appointments/editAppointments.cy.ts
server/@types/activitiesAPI/types.ts
server/routes/appointments/create-and-edit/editAppointmentJourney.ts
server/routes/appointments/create-and-edit/handlers/startJourney.ts
server/services/editAppointmentService.test.ts
server/services/editAppointmentService.ts

The primary purpose of this PR is to redirect back to the bulk appointment set page after deleting a bulk appointment occurrence.
I've also added some minor logic and test improvements.

SAA-926: Redirect deleted bulk appointment occurrences to set page

---

server/routes/activities/daily-attendance-summary/handlers/notAttendedSelectDate.test.ts
server/routes/activities/daily-attendance-summary/handlers/notAttendedSelectDate.ts
server/routes/activities/daily-attendance-summary/index.ts
server/views/pages/activities/not-attended/select-date.njk
server/views/pages/activities/record-attendance/home.njk

Adds a new tile and date selection page to access the daily not attended list.

SAA-755: Added all not attended tile

---

frontend/utilities/_table.scss
server/views/pages/appointments/partials/occurrence-movement-slip.njk
server/views/pages/appointments/search/results.njk

SAA-940: Escape movement slip and correctly display unmapped prisoner details on search results

---

server/routes/activities/allocate-to-activity/handlers/startDate.test.ts
server/routes/activities/allocate-to-activity/handlers/startDate.ts
server/routes/activities/allocate-to-activity/handlers/startJourney.ts
server/routes/activities/allocate-to-activity/journey.ts
server/routes/activities/allocation-dashboard/handlers/checkAllocation.ts
server/routes/activities/change-of-circumstances/handlers/selectPeriodForChanges.ts
server/routes/activities/daily-attendance-summary/handlers/notAttendedSelectDate.ts
server/routes/activities/daily-attendance-summary/handlers/selectPeriod.ts
server/routes/activities/record-attendance/handlers/selectPeriod.ts
server/routes/activities/unlock-list/handlers/selectDateAndLocation.ts
server/validators/dateIsSameOrBefore.test.ts
server/validators/dateIsSameOrBefore.ts

SAA-1035 validating allocation start date on create against the activity end date (if the activity has one).

---

server/views/pages/activities/allocation-dashboard/activities.njk
server/views/pages/activities/allocation-dashboard/allocation-dashboard.njk
server/views/pages/activities/daily-attendance-summary/attendances.njk
server/views/pages/activities/daily-attendance-summary/cancelled-sessions.njk
server/views/pages/activities/manage-schedules/activities-dashboard.njk
server/views/pages/activities/record-attendance/activities.njk
server/views/pages/activities/record-attendance/attendance-list.njk

SAA-1053: Escape unsafe html

---

server/nunjucks/nunjucksSetup.ts
server/utils/utils.ts
server/views/pages/appointments/bulk-appointment-details/bulk-appointment.njk
server/views/pages/appointments/details/appointment.njk
server/views/pages/appointments/occurrence-details/occurrence.njk
server/views/pages/appointments/partials/occurrence-movement-slip.njk
server/views/pages/appointments/partials/service-user-name.njk
server/views/partials/showProfileLink.njk

Minor content changes for missing / incomplete appointments data

SAA-941: Appointments content changes

---

server/routes/appointments/search/handlers/search.test.ts
server/routes/appointments/search/handlers/search.ts
server/views/pages/appointments/search/results.njk
server/views/pages/appointments/search/results.njk.test.ts

Allows appointments to be filtered by either their full appointment name or by category

SAA-919: Filter appointments by category or name

---

frontend/all.js
frontend/components/_all.scss
frontend/components/form-spinner/_form-spinner.scss
frontend/components/form-spinner/form-spinner.js
server/views/pages/appointments/create-and-edit/check-answers.njk

Adds loading spinner to create appointment requests.
https://github.com/ministryofjustice/hmpps-activities-management/assets/125488090/1966153c-3069-4af9-bab7-ed53d8894e0d

SAA-1071: Adds form loading spinner

---

frontend/components/form-spinner/form-spinner.js

Small change to add 1 second delay to loading overlay.

SAA-1071: Adds loading spinner delay

---

integration_tests/e2e/appointments/editAppointments.cy.ts
server/routes/appointments/create-and-edit/createRoutes.ts
server/routes/appointments/create-and-edit/editRoutes.ts
server/routes/appointments/create-and-edit/handlers/dateAndTime.test.ts
server/routes/appointments/create-and-edit/handlers/dateAndTime.ts
server/routes/appointments/create-and-edit/handlers/reviewPrisoners.test.ts
server/routes/appointments/create-and-edit/handlers/reviewPrisoners.ts
server/routes/appointments/create-and-edit/handlers/schedule.test.ts
server/routes/appointments/create-and-edit/handlers/schedule.ts
server/utils/editAppointmentUtils.ts
server/views/pages/appointments/create-and-edit/apply-to.njk
server/views/pages/appointments/create-and-edit/apply-to.njk.test.ts
server/views/pages/appointments/create-and-edit/date-and-time.njk
server/views/pages/appointments/create-and-edit/date-and-time.njk.test.ts
server/views/pages/appointments/create-and-edit/schedule.njk
server/views/pages/appointments/create-and-edit/schedule.njk.test.ts

Adds view schedule to edit appointment journey.
**Edit date/time**
**Add prisoners**

SAA-980: Adds view schedule to edit journey

---

server/routes/activities/allocation-dashboard/handlers/allocationDashboard.ts
server/views/pages/activities/allocation-dashboard/allocation-dashboard.njk

Small bug fix for missing slots
**Before**
**After**

SAA-1006: Fixes missing slots bug

---

server/routes/appointments/create-and-edit/handlers/startJourney.ts
server/views/pages/activities/record-attendance/not-attended-reason.njk
server/views/pages/appointments/create-and-edit/schedule.njk
server/views/pages/appointments/create-and-edit/schedule.njk.test.ts
server/views/pages/appointments/partials/service-user-name.njk
server/views/pages/appointments/search/results.njk
server/views/partials/attendance/otherEvent.njk
server/views/partials/showProfileLink.njk
server/views/partials/showUnlockEvents.njk

Minor appointments content updates

SAA-941: Content updates

---

server/routes/activities/create-an-activity/handlers/capacity.test.ts
server/routes/activities/create-an-activity/handlers/capacity.ts
server/routes/activities/create-an-activity/handlers/riskLevel.test.ts
server/routes/activities/create-an-activity/handlers/riskLevel.ts

Updates error messages on the work place risk assessment and capacity page
**Workplace risk assessment**
**Capacity**

SAA-1098: Error message updates

---

server/views/pages/appointments/create-and-edit/schedule.njk
server/views/pages/appointments/create-and-edit/schedule.njk.test.ts

Fixes incorrect appointment date bug when editing appointment date.

SAA-980: Fixed appointment date bug

---

server/views/pages/activities/record-attendance/activities.njk

- Made search bar two thirds width
- Added clear button to search bar
**Before**
**After**

SAA-1089: Minor updates to record attendance activity dashboard

---

server/routes/activities/create-an-activity/handlers/capacity.ts
server/routes/activities/create-an-activity/handlers/confirmCapacity.test.ts
server/routes/activities/create-an-activity/handlers/confirmCapacity.ts
server/routes/activities/create-an-activity/index.ts
server/routes/activities/manage-schedules/index.ts
server/views/pages/activities/create-an-activity/confirm-capacity.njk

Content updates to confirm capacity page. I've also moved this page into the create activity directory.

SAA-1089: Confirm capacity page updates

---

server/routes/activities/create-an-activity/handlers/riskLevel.test.ts
server/routes/activities/create-an-activity/handlers/riskLevel.ts
server/views/pages/activities/create-an-activity/check-pay.njk

Fixes broken back link on the check pay page of the create journey

SAA-1174: Fixes back link on check pay page

---

server/routes/activities/allocate-to-activity/handlers/endDate.test.ts
server/routes/activities/allocate-to-activity/handlers/endDate.ts
server/routes/activities/allocate-to-activity/handlers/startDate.test.ts
server/routes/activities/allocate-to-activity/handlers/startDate.ts
server/routes/activities/allocation-dashboard/handlers/endDate.test.ts
server/routes/activities/allocation-dashboard/handlers/endDate.ts
server/routes/activities/allocation-dashboard/handlers/startDate.test.ts
server/routes/activities/allocation-dashboard/handlers/startDate.ts
server/routes/activities/deallocate-from-activity/handlers/deallocationDate.ts
server/views/pages/activities/allocation-dashboard/allocation-dashboard.njk
server/views/pages/activities/allocation-dashboard/allocation-dashboard.njk.test.ts
server/views/pages/activities/allocation-dashboard/end-date.njk
server/views/pages/activities/allocation-dashboard/pay-band.njk
server/views/pages/activities/deallocate-from-activity/deallocation-date.njk
server/views/pages/activities/manage-schedules/activities-dashboard.njk
server/views/pages/activities/manage-schedules/check-pay.njk
server/views/pages/activities/manage-schedules/view-activity.njk
server/views/pages/activities/waitlist-application/edit-request-date.njk

SAA-1200: Content sweep changes

---

server/@types/activitiesAPI/index.d.ts
server/routes/activities/waitlist-application/handlers/view-and-edit/viewApplication.test.ts
server/routes/activities/waitlist-application/handlers/view-and-edit/viewApplication.ts
server/views/pages/activities/waitlist-application/view-application.njk

Updates "last updated" status text to use new `statusUpdatedTime`, and hides if null.

SAA-1194: Status timestamp updates

---

server/routes/activities/record-attendance/handlers/notAttendedReason.test.ts
server/routes/activities/record-attendance/handlers/notAttendedReason.ts

This fixes bugs related to the hidden form elements of other attendance reasons being submitted and sent to the API.

SAA-1107: Default attendance values for reason

---

server/views/pages/activities/record-attendance/attendance-list.njk

Fixes missing attendance counts

SAA-1122: Fixed attendance counts

---

server/@types/express/index.d.ts
server/routes/activities/create-an-activity/handlers/confirmation.ts
server/routes/activities/create-an-activity/handlers/startJourney.ts

SAA-1038 - Added SAA-Activity-Created event

---

server/enum/dateOption.ts
server/nunjucks/nunjucksSetup.ts
server/routes/activities/index.ts
server/routes/activities/movement-list/handlers/chooseDetails.test.ts
server/routes/activities/movement-list/handlers/chooseDetails.ts
server/routes/activities/movement-list/index.ts
server/views/pages/activities/home/home.njk
server/views/pages/activities/movement-list/choose-details.njk
server/views/pages/activities/unlock-list/home.njk

Changes the unlock tile header and content:
Adds movement list tile to unlock sub menu:
Adds first page in movement lists journey - choose details

SAA-1201: Tile updates and initial navigation for movement lists

---

frontend/components/movement-list/_movement-list.scss
frontend/utilities/_misc.scss
frontend/utilities/_print.scss
server/views/pages/activities/movement-list/location-events.njk

SAA-553: Movement list print styles

---

server/routes/activities/create-an-activity/handlers/removeFlatRate.ts
server/routes/activities/create-an-activity/handlers/removePay.ts
server/views/pages/activities/create-an-activity/check-pay.njk

Fixes a few links and redirects on the pay pages of the create journey

SAA-1174: Pay rate CTA and back link fixes

---

frontend/application-ie8.scss
frontend/application.scss
gruntfile.js
package-lock.json
package.json
server/nunjucks/nunjucksSetup.ts

Local build improvements for live development

Local build improvements

---

server/routes/activities/record-attendance/handlers/notAttendedReason.test.ts
server/routes/activities/record-attendance/handlers/notAttendedReason.ts

Fixes bug where payment issued for sick & rest when no pay is selected

SAA-1217: Fix bug - no pay issued when pay not selected

---

frontend/components/tabs/_tabs.scss

Updates tab component styling with focus state and accessible hover colour.

SAA-1222: Accessible tabs

---

server/views/partials/showUnlockEvents.njk

Fixed missing unlock list end date

SAA-1202: Fixed unlock list end date

---

server/@types/metricsEvents.ts
server/data/metricsEvent.ts
server/routes/activities/allocate-to-activity/handlers/confirmation.test.ts
server/routes/activities/allocate-to-activity/handlers/confirmation.ts
server/routes/activities/allocate-to-activity/handlers/startJourney.test.ts
server/routes/activities/allocate-to-activity/handlers/startJourney.ts
server/routes/activities/allocate-to-activity/index.ts
server/routes/activities/create-an-activity/handlers/confirmation.test.ts
server/routes/activities/create-an-activity/handlers/confirmation.ts
server/routes/activities/create-an-activity/handlers/startJourney.test.ts
server/routes/activities/create-an-activity/handlers/startJourney.ts
server/routes/activities/create-an-activity/index.ts
server/routes/activities/waitlist-application/handlers/create/checkAnswers.test.ts
server/routes/activities/waitlist-application/handlers/create/checkAnswers.ts
server/routes/activities/waitlist-application/handlers/create/startJourney.test.ts
server/routes/activities/waitlist-application/handlers/create/startJourney.ts
server/routes/activities/waitlist-application/index.ts
server/routes/appointments/create-and-edit/handlers/confirmation.test.ts
server/routes/appointments/create-and-edit/handlers/startJourney.test.ts
server/services/editAppointmentService.test.ts

Added journey start metric events

SAA-1231: Added UI metrics

---

server/views/pages/activities/change-of-circumstances/view-events.njk

Fixes sticky select banner layout
**Before**
**After**

SAA-1268: Fixed sticky select banner layout bug

---

frontend/components/_all.scss
frontend/components/appointment-details/_appointment-details.scss
server/views/pages/appointments/appointment/details.njk
server/views/pages/appointments/partials/attendee-list.njk

SAA-1207: Print appointment attendee list

---

server/views/pages/appointments/create-and-edit/schedule.njk
server/views/pages/appointments/create-and-edit/schedule.njk.test.ts

Small update to reset journey when clicking "add a new list" button after removing all prisoners from appointment set.

SAA-1043: Reset journey if all prisoners removed

---

server/utils/fixtures/appointment-set/appointment-set-empty-rows.csv
server/utils/prisonerListCsvParser.test.ts
server/utils/prisonerListCsvParser.ts

Minor change to CSV parser to ignore empty rows.

SAA-1044: Ignore empty rows in CSV uploads

---

frontend/utilities/_print.scss

SAA-1290: Increase left and right print margins

---

server/routes/activities/manage-schedules/handlers/helpers/incentiveLevelPayMappingUtil.ts
server/views/pages/activities/manage-schedules/check-pay.njk

Fixes a couple of bugs when editing activity pay

SAA-1235: Bug fixes

---

integration_tests/e2e/recordAttendance.cy.ts
integration_tests/e2e/recordNonAttendance.cy.ts
integration_tests/pages/recordAttendance/selectPeriod.ts
server/routes/activities/daily-attendance-summary/handlers/notAttendedSelectDate.test.ts
server/routes/activities/daily-attendance-summary/handlers/notAttendedSelectDate.ts
server/routes/activities/daily-attendance-summary/handlers/selectPeriod.test.ts
server/routes/activities/daily-attendance-summary/handlers/selectPeriod.ts
server/routes/activities/movement-list/handlers/chooseDetails.test.ts
server/routes/activities/movement-list/handlers/chooseDetails.ts
server/routes/activities/record-attendance/handlers/selectPeriod.test.ts
server/routes/activities/record-attendance/handlers/selectPeriod.ts
server/routes/activities/unlock-list/handlers/selectDateAndLocation.test.ts
server/routes/activities/unlock-list/handlers/selectDateAndLocation.ts
server/utils/datePickerUtils.ts
server/validators/DateValidator.test.ts
server/validators/DateValidator.ts
server/views/components/hmppsDatePicker.njk
server/views/pages/activities/daily-attendance-summary/select-period.njk
server/views/pages/activities/movement-list/choose-details.njk
server/views/pages/activities/record-attendance/select-period.njk
server/views/pages/activities/unlock-list/select-date-and-location.njk
server/views/pages/appointments/create-and-edit/appointment-set/date.njk
server/views/pages/appointments/create-and-edit/date-and-time.njk
server/views/pages/appointments/search/select-date.njk

Adds date picker to:
- Unlock List
- Movement List
- Attendance pages (Record attendance, daily attendance summary, not attended)

SAA-1289: Activity date pickers #1

---

frontend/application-insights-setup.js
frontend/index.js
package-lock.json
package.json
server/middleware/setUpWebSecurity.ts
server/nunjucks/nunjucksSetup.ts
server/views/layout.njk

This adds app insights page view tracking allowing us to pull client metrics such as:
- Most common browsers
- Unique sessions
- Frequently visited pages
- Time on a page
We could also use this to support client-side events such as clicking print buttons.

SAA-1304: Track application pageview data

---

server/views/pages/appointments/home/index.njk
server/views/pages/home/index.njk

https://github.com/ministryofjustice/hmpps-activities-management/assets/9396346/16111fd2-a0ae-45d4-9d2f-16044279baab

SAA-1303: Appointment attendance tile content change

---

frontend/components/filters/_filters.scss
frontend/components/sticky-select/_sticky-select.scss
server/@types/activitiesAPI/index.d.ts
server/@types/activitiesAPI/types.ts
server/config.ts
server/data/activitiesApiClient.test.ts
server/data/activitiesApiClient.ts
server/enum/waitingListStatus.ts
server/routes/activities/index.ts
server/routes/activities/waitlist-application/handlers/create/status.test.ts
server/routes/activities/waitlist-application/handlers/create/status.ts
server/routes/activities/waitlist-application/handlers/view-and-edit/editStatus.test.ts
server/routes/activities/waitlist-application/handlers/view-and-edit/editStatus.ts
server/routes/activities/waitlist-application/handlers/view-and-edit/viewApplication.test.ts
server/routes/activities/waitlist-application/handlers/view-and-edit/viewApplication.ts
server/routes/activities/waitlist-application/journey.ts
server/routes/activities/waitlist-dashboard/handlers/dashboard.test.ts
server/routes/activities/waitlist-dashboard/handlers/dashboard.ts
server/routes/activities/waitlist-dashboard/index.ts
server/services/activitiesService.test.ts
server/services/activitiesService.ts
server/views/components/sticky-select.njk
server/views/pages/activities/manage-allocations/home.njk
server/views/pages/activities/waitlist-application/edit-status.njk
server/views/pages/activities/waitlist-application/status.njk
server/views/pages/activities/waitlist-application/view-application.njk
server/views/pages/activities/waitlist-dashboard/dashboard.njk

Adds waiting list dashboard page allowing users to search and manage waiting list applications within a prison.

SAA-1262: Waiting lists dashboard

---

server/views/pages/activities/change-of-circumstances/view-events.njk

**LOW RISK**
PR to support changes in this related [PR](https://github.com/ministryofjustice/hmpps-activities-management-api/pull/649) (and yes the tag says 'RELEASE' for all of them.  The CoC needs some UR work to be carried out)

SAA-1335 updating the change of circumstances template to support the current release events use by the service.

---

server/routes/activities/waitlist-dashboard/handlers/dashboard.test.ts
server/routes/activities/waitlist-dashboard/handlers/dashboard.ts

Fixes broken redirect when allocating on waiting list dashboard.

SAA-1262: Fixed redirect

---

server/routes/appointments/search/handlers/search.test.ts
server/routes/appointments/search/handlers/search.ts

Updates prisoner number filter on the appointments dashboard to support case insensitive prisoner number matching

SAA-994: Appointments dashboard prisoner number filter

---

server/views/pages/appointments/partials/attendee-list.njk

**Issue:** Print Attendance View not aligned with header.
Corrected: Corrected according to the header.

SAA-1317 Print Attendance view corrected properly

---

server/routes/activities/manage-allocations/handlers/exclusions.test.ts

SAA-1395: Fixed exclusions unit test

---

server/routes/activities/manage-allocations/handlers/endDate.test.ts
server/routes/activities/manage-allocations/handlers/endDate.ts
server/routes/activities/manage-allocations/handlers/startDate.ts
server/routes/activities/manage-allocations/handlers/startJourney.test.ts
server/routes/activities/manage-allocations/handlers/startJourney.ts
server/routes/activities/manage-allocations/middlewares/initialiseEditAndRemoveJourney.test.ts
server/routes/activities/manage-allocations/middlewares/initialiseEditAndRemoveJourney.ts

Fixes deallocation validation bug.
Before
After

SAA-1402: Fixes deallocation validation bug

---

integration_tests/fixtures/activitiesApi/getSchedule.json
server/routes/activities/allocation-dashboard/handlers/allocationDashboard.test.ts
server/routes/activities/allocation-dashboard/handlers/allocationDashboard.ts
server/routes/activities/manage-allocations/handlers/checkAnswers.ts
server/routes/activities/manage-allocations/handlers/endDate.test.ts
server/routes/activities/manage-allocations/handlers/endDate.ts
server/routes/activities/manage-allocations/handlers/endDateOption.test.ts
server/routes/activities/manage-allocations/handlers/endDateOption.ts
server/routes/activities/manage-allocations/handlers/payBand.ts
server/routes/activities/manage-allocations/handlers/startJourney.test.ts
server/routes/activities/manage-allocations/handlers/startJourney.ts
server/routes/activities/manage-allocations/journey.ts
server/routes/activities/manage-allocations/middlewares/initialiseEditAndRemoveJourney.ts
server/services/activitiesService.ts
server/views/pages/activities/manage-allocations/before-you-allocate.njk
server/views/pages/activities/manage-allocations/check-answers.njk
server/views/pages/activities/manage-allocations/view-allocation.njk

Adds support for allocating to zero pay activities

SAA-1392: Zero pay activity allocation create and edit journeys 

---

helm_deploy/values-dev.yaml
integration_tests/e2e/createActivity.cy.ts
server/config.ts
server/nunjucks/nunjucksSetup.ts
server/routes/activities/create-an-activity/handlers/riskLevel.test.ts
server/routes/activities/create-an-activity/handlers/riskLevel.ts

Adds feature flag to create journey to prevent creation of zero pay activities.

SAA-1358: Feature flag

---

.circleci/config.yml

Updates NPM version. Missed this in my original PR (https://github.com/ministryofjustice/hmpps-activities-management/pull/634).

SAA-1349: Update npm version

---

server/routes/activities/record-attendance/handlers/notAttendedReason.test.ts
server/routes/activities/record-attendance/handlers/notAttendedReason.ts
server/views/pages/activities/record-attendance/not-attended-reason.njk

- Ignores pay inputs during validation if activity is unpaid
- Removes pay radio selection from "OTHER" attendance reason.

SAA-1398: Validation updates

---

server/@types/activitiesAPI/index.d.ts
server/routes/activities/create-an-activity/createAndEditRoutes.ts
server/routes/activities/create-an-activity/handlers/checkPay.ts
server/routes/activities/create-an-activity/handlers/pay.test.ts
server/routes/activities/create-an-activity/handlers/pay.ts
server/routes/activities/create-an-activity/handlers/payOption.test.ts
server/routes/activities/create-an-activity/handlers/payOption.ts
server/routes/activities/create-an-activity/middlewares/initialiseEditJourney.ts
server/views/pages/activities/create-an-activity/edit-pay.njk
server/views/pages/activities/manage-activities/view-activity.njk

Adds support for editing unpaid activities

SAA-1394: Zero pay – edit activity journey

---

server/routes/activities/create-an-activity/handlers/payOption.test.ts
server/routes/activities/create-an-activity/handlers/payOption.ts
server/views/pages/activities/allocation-dashboard/allocation-dashboard.njk
server/views/pages/activities/create-an-activity/check-answers.njk
server/views/pages/activities/manage-activities/view-activity.njk

A few minor content updates that came out of Stuart's zero pay content review.

SAA-1358: Zero pay content updates

---

helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Enables zero pay activities on prod and pre-prod environments.

SAA-1358: Enable zero pay on prod and preprod

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
integration_tests/e2e/createActivity.cy.ts
server/config.ts
server/nunjucks/nunjucksSetup.ts
server/routes/activities/create-an-activity/handlers/riskLevel.test.ts
server/routes/activities/create-an-activity/handlers/riskLevel.ts

Removes zero pay rate feature toggle.

SAA-1422: Remove zero pay rate feature toggle

---

server/views/pages/appointments/appointment-set/details.njk

Small change to make appointment set attendee list printable.

SAA-1433: Appointment set print view

---

server/views/pages/activities/record-attendance/attendance-list.njk

Adds inset text when recording future attendance

SAA-1450: Future attendance inset text

---

server/routes/activities/unlock-list/handlers/plannedEvents.test.ts
server/routes/activities/unlock-list/handlers/plannedEvents.ts
server/views/pages/activities/unlock-list/planned-events.njk
server/views/pages/appointments/appointment-set/details.njk

Adds metric event for printing appointment set attendee lists. Also added a fix to pull the unlock list location name for unlock list events.

SAA-1441: Appointment set printed list event

---

integration_tests/e2e/allocateToActivity.cy.ts
integration_tests/e2e/recordAttendance.cy.ts
integration_tests/e2e/recordNonAttendance.cy.ts
integration_tests/pages/allocateToActivity/payBand.ts
integration_tests/pages/page.ts
integration_tests/pages/recordAttendance/selectPeriod.ts
server/views/pages/activities/create-an-activity/days-and-times.njk
server/views/pages/activities/daily-attendance-summary/select-period.njk
server/views/pages/activities/manage-activities/view-activity.njk
server/views/pages/activities/manage-allocations/deallocation-reason.njk
server/views/pages/activities/manage-allocations/pay-band.njk
server/views/pages/activities/manage-allocations/remove-date-option.njk
server/views/pages/activities/manage-allocations/start-date.njk
server/views/pages/activities/record-attendance/activities.njk
server/views/pages/activities/record-attendance/cancel-session/confirm.njk
server/views/pages/activities/record-attendance/remove-pay.njk
server/views/pages/activities/record-attendance/reset-attendance.njk
server/views/pages/activities/record-attendance/select-period.njk
server/views/pages/activities/record-attendance/uncancel-session/confirm.njk
server/views/pages/activities/unlock-list/planned-events.njk
server/views/pages/activities/waitlist-application/check-answers.njk
server/views/pages/not-rolled-out.njk

Some minor content updates to align content across service.
This change includes updates to CTA button text to use "Continue" / "Confirm" where appropriate, and updates to date formats to use standard format (Tuesday, 12 December 2023).

SAA-1454: Minor content updates

---

server/routes/activities/allocation-dashboard/handlers/allocationDashboard.test.ts
server/routes/activities/allocation-dashboard/handlers/allocationDashboard.ts

Updates the logic of the work filter on the waitlist tab to consider if other allocations count towards employment.

SAA-1460: Not in work filter update

---

server/errorHandler.test.ts
server/errorHandler.ts
server/middleware/routeAuthMiddleware.test.ts
server/middleware/routeAuthMiddleware.ts
server/nunjucks/nunjucksSetup.ts
server/views/pages/403.njk
server/views/pages/404.njk
server/views/pages/error.njk

Updates error pages with user friendly content
**500**
**403**
**404**

SAA-1033: Friendly error pages

---

server/routes/activities/record-attendance/handlers/removePay.test.ts
server/routes/activities/record-attendance/handlers/removePay.ts
server/views/pages/activities/record-attendance/remove-pay.njk

Adds validation to case note input on remove pay page

SAA-1492: Added remove pay form validation

---

server/views/pages/activities/record-attendance/not-attended-reason.njk

Small styling fix.
**Before**
**After**

SAA-1490: Styling fix

---

server/views/pages/appointments/search/results.njk
server/views/pages/appointments/search/results.njk.test.ts

Dev Review:
Before changes: 
1. Time Period to Session
2. Spacing between Afternoon and Appointment Name
3. Font size for Session to be same across other names.
After changes:
1. Changed Time Period to Session.
2. Changed the spaces for Afternoon and Appointment Name.

SAA-1140 Changed Time Period to Session and spacing

---

frontend/components/appointment-schedule/_appointment-schedule.scss
server/views/pages/appointments/create-and-edit/schedule.njk
server/views/pages/appointments/create-and-edit/schedule.njk.test.ts

Minor styling update to the appointment cards on the appointment review schedule page.
**Before**
**After**

SAA-1001: Styling update for review schedule page

---

frontend/utilities/_misc.scss
server/views/pages/appointments/create-and-edit/schedule.njk

Review Schedule:
Before:
Activity: text wrap 
After:
Activity: text-warp with new css

SAA-1224 text wrap for type added with new css.

---

server/routes/activities/daily-attendance-summary/handlers/notAttendedSelectDate.test.ts
server/routes/activities/daily-attendance-summary/handlers/notAttendedSelectDate.ts
server/routes/activities/record-attendance/handlers/cancel-session/confirmation.test.ts
server/routes/activities/record-attendance/handlers/cancel-session/confirmation.ts
server/routes/activities/record-attendance/handlers/editAttendance.test.ts
server/routes/activities/record-attendance/handlers/editAttendance.ts
server/routes/activities/record-attendance/handlers/resetAttendance.test.ts
server/routes/activities/record-attendance/handlers/resetAttendance.ts
server/routes/activities/record-attendance/handlers/uncancel-session/confirmation.test.ts
server/routes/activities/record-attendance/handlers/uncancel-session/confirmation.ts

Updated error messaging for validation in attendance journey for:

SAA-1119: Update validation error messages

---

server/@types/activitiesAPI/index.d.ts
server/services/editAppointmentService.test.ts
server/services/editAppointmentService.ts
server/views/pages/appointments/appointment-series/details.njk
server/views/pages/appointments/appointment-set/details.njk
server/views/pages/appointments/appointment/details.njk
server/views/pages/appointments/partials/attendee-list.njk

Updates to surface deleted appointments on the series details and set details pages.

SAA-1504: Show deleted appointments

---

integration_tests/e2e/allocateToActivity.cy.ts
integration_tests/e2e/appointments/createAppointment.cy.ts
integration_tests/e2e/appointments/createRepeatAppointment.cy.ts
integration_tests/e2e/createActivity.cy.ts
integration_tests/e2e/deallocateFromActivity.cy.ts
integration_tests/e2e/recordAttendance.cy.ts
integration_tests/e2e/recordNonAttendance.cy.ts
server/views/pages/activities/home/home.njk
server/views/pages/activities/manage-allocations/home.njk
server/views/pages/activities/record-attendance/home.njk
server/views/pages/activities/unlock-list/home.njk
server/views/pages/appointments/home/index.njk
server/views/pages/home/index.njk

SAA-1449: Amend content on main tiles and back links

---

.circleci/config.yml

Change to use new activities and appointments team alerts channel.

SAA-1548 use team alerts channel.

---

server/views/pages/activities/waitlist-dashboard/dashboard.njk

Add release date column to the waiting list dashboard and merge the requester and request date columns

SAA-1571 Add release date column to the waiting list dashboard and merge requester and request date

---

server/views/pages/appointments/create-and-edit/location.njk

SAA-1587: Fix appointment location heading size

---

server/views/pages/activities/daily-attendance-summary/cancelled-sessions.njk
server/views/pages/activities/daily-attendance-summary/daily-summary.njk
server/views/pages/activities/daily-attendance-summary/select-period.njk
server/views/pages/activities/manage-allocations/before-you-allocate.njk
server/views/pages/activities/record-attendance/attendance-list.njk
server/views/partials/earliestReleaseDate.njk
server/views/partials/splitLine.njk

SAA-1620 correcting the date formatting for single digit days to remove zero prefix.

---

server/routes/activities/create-an-activity/handlers/name.ts

Update content changes requested in team review session

SAA-1128: Amend error content

---

feature.env
integration_tests/e2e/health.cy.ts
integration_tests/index.d.ts
integration_tests/mockApis/stubs.ts
integration_tests/mockApis/wiremock.ts
integration_tests/support/commands.ts
server/services/healthCheck.ts

SAA-1633: Add dependant APIs to health check

---

server/data/activitiesApiClient.test.ts
server/data/activitiesApiClient.ts
server/routes/activities/daily-attendance-summary/handlers/cancelledSessions.test.ts
server/routes/activities/daily-attendance-summary/handlers/cancelledSessions.ts
server/routes/activities/daily-attendance-summary/handlers/dailySummary.test.ts
server/routes/activities/daily-attendance-summary/handlers/dailySummary.ts
server/services/activitiesService.test.ts
server/services/activitiesService.ts
server/views/pages/activities/daily-attendance-summary/daily-summary.njk

- Uses feature toggle
- Uses changes in API to get cancelled schedule activities more efficiently

SAA-1509: Update attendance summary screen to include non-attendance activities

---

server/routes/activities/daily-attendance-summary/handlers/attendance.test.ts
server/routes/activities/daily-attendance-summary/handlers/attendance.ts

Exclude attendances where attendance is not required for activity from All Not Yet Attended and Absences screen

SAA-1508: Exclude attendance not required activities from All Not Yet Attended and All Absences screens

---

server/views/pages/activities/daily-attendance-summary/attendances.njk
server/views/pages/activities/daily-attendance-summary/cancelled-sessions.njk
server/views/pages/activities/daily-attendance-summary/daily-summary.njk
server/views/pages/activities/daily-attendance-summary/suspended-prisoners.njk

A gallery of blue refresh buttons

SAA-1630 blue refresh buttons

---

server/views/pages/activities/home/home.njk
server/views/pages/activities/suspensions/confirmation.njk
server/views/pages/activities/suspensions/view-allocations.njk
server/views/partials/activities/suspension-badge.njk

SAA-1647: Content changes

---

server/views/pages/activities/record-attendance/attendance-list.njk

**Attendance required activity - Attendance list print view**
**Attendance not required activity - Attendance list print view**

SAA-1507: Update non attendance list print functionality

---

server/views/pages/activities/daily-attendance-summary/attendances.njk

SAA-1164: Add session column to display time slot and change session column title to activity

---

package-lock.json
package.json
server/routes/activities/create-an-activity/handlers/daysAndTimes.test.ts
server/routes/activities/create-an-activity/handlers/daysAndTimes.ts
server/routes/activities/create-an-activity/handlers/endDate.test.ts
server/routes/activities/create-an-activity/handlers/endDate.ts
server/routes/activities/create-an-activity/handlers/startDate.test.ts
server/routes/activities/create-an-activity/handlers/startDate.ts
server/utils/helpers/activityScheduleValidator.test.ts
server/utils/helpers/activityScheduleValidator.ts

Verify start date, end date and weekly slots when creating an activity or editing.

SAA-631: Validate activity date and schedules

---

server/routes/activities/manage-allocations/handlers/viewAllocation.test.ts
server/routes/activities/manage-allocations/handlers/viewAllocation.ts
server/views/pages/activities/manage-allocations/view-allocation.njk

Added the extra detail to the allocation view screen

SAA-1684: Allocation view. Display who allocated the prisoner to the activity

---

server/routes/activities/manage-allocations/handlers/viewAllocation.test.ts
server/routes/activities/manage-allocations/handlers/viewAllocation.ts

SAA-1684: Allocation view. Handle the case where an allocated by user is not found. e.g. MIGRATION

---

server/views/pages/activities/create-an-activity/attendance-required.njk

SAA-1607: Update activity attendance option hint text

---

integration_tests/e2e/activities/attendance/activitiesAttendance.cy.ts
integration_tests/e2e/activities/attendance/attendanceNotRequired.cy.ts
integration_tests/e2e/activities/attendance/multipleActivities.cy.ts
integration_tests/e2e/activities/attendance/recordAttendance.cy.ts
integration_tests/e2e/activities/attendance/recordNonAttendance.cy.ts
server/routes/activities/record-attendance/handlers/activities.test.ts
server/routes/activities/record-attendance/handlers/activities.ts
server/routes/activities/record-attendance/index.ts
server/services/fixtures/attendance_summary_1.json
server/views/pages/activities/record-attendance/activities.njk
server/views/pages/activities/record-attendance/attendance-list-multiple.njk

SAA-1740: Add more location filter options to find activities for mark attendance

---

frontend/components/_all.scss
frontend/components/attendance-activities/_attendance-activities.scss
server/views/pages/activities/record-attendance/activities.njk
server/views/partials/attendance/activitiesTable.njk

Fix issues with attendance activities view.
Make Filters header plural:
Add Location header, use smaller checkboxes and lower-case l in locations "All locations":
Improve no results table:
Add small right padding fro numerics in table:

SAA-1737: Fix attendance activities view issues

---

integration_tests/e2e/activities/attendance/multipleActivities.cy.ts
integration_tests/pages/recordAttendance/attendanceListMultiple.ts
server/routes/activities/record-attendance/handlers/activities.ts
server/routes/activities/record-attendance/handlers/attendanceList.test.ts
server/routes/activities/record-attendance/handlers/attendanceList.ts
server/routes/activities/record-attendance/recordAttendanceRequests.ts
server/views/pages/activities/record-attendance/attendance-list-multiple.njk

- Change back link in attendance list to return to activities page
- Fix the view / edit link in attendance list page

SAA-1737: Fix back link and view link in attendance list

---

frontend/components/attendance-activities/_attendance-activities.scss
frontend/components/sticky-select/_sticky-select.scss
frontend/utilities/_table.scss
server/views/partials/attendance/activitiesTable.njk

SAA-1842: Blue sticky bar width, activity attendance table CSS improvements

---

integration_tests/e2e/activities/attendance/multipleActivities.cy.ts
server/routes/activities/record-attendance/handlers/activities.test.ts
server/routes/activities/record-attendance/handlers/activities.ts
server/routes/activities/record-attendance/handlers/attendanceList.test.ts
server/routes/activities/record-attendance/handlers/attendanceList.ts
server/views/pages/activities/record-attendance/attendance-list-multiple.njk
server/views/pages/activities/record-attendance/attendance-list-single.njk
server/views/partials/formatSessions.njk

Reverts ministryofjustice/hmpps-activities-management#970

Revert "SAA-1737: Redirect to single activity session view if only one instances is selected for updating attendance"

---

server/@types/bookAVideoLinkApi/types.ts
server/config.ts
server/routes/appointments/video-link-booking/handlers/videoLinkDetails.test.ts
server/routes/appointments/video-link-booking/handlers/videoLinkDetails.ts
server/routes/appointments/video-link-booking/index.ts
server/views/pages/appointments/appointment/details.njk
server/views/pages/appointments/video-link-booking/details.njk

BAVL-236: View individual video link appointments with movement slips and attendance

---

server/views/pages/activities/movement-list/location-events.njk

SAA-1933: Remove sort on activity and clashing event columns

---

server/views/pages/appointments/search/results.njk

BAVL-276: Printable appointments dashboard as continegency for daily video booking schedule

---

integration_tests/e2e/activities/attendance/multipleActivities.cy.ts
integration_tests/fixtures/activitiesApi/getScheduledInstance11.json
integration_tests/pages/recordAttendance/activitiesPage.ts
integration_tests/pages/recordAttendance/attendanceListMultiple.ts
server/views/pages/activities/record-attendance/attendance-list-multiple.njk
server/views/partials/attendance/activitiesTable.njk

SAA-1929: Show times instead of slots for record attendance for multiple activities

---

server/routes/activities/create-an-activity/handlers/sessionTimes.test.ts
server/routes/activities/create-an-activity/handlers/sessionTimes.ts
server/utils/helpers/activityTimeSlotMappers.ts
server/views/pages/activities/create-an-activity/session-times.njk

SAA-1940: select custom start and end session times. Validation

---

integration_tests/e2e/activities/createActivity.cy.ts
integration_tests/e2e/activities/createActivityWithFoundationTier.cy.ts
server/routes/activities/create-an-activity/handlers/daysAndTimes.test.ts
server/routes/activities/create-an-activity/handlers/daysAndTimes.ts
server/routes/activities/create-an-activity/handlers/sessionTimes.test.ts
server/routes/activities/create-an-activity/handlers/sessionTimes.ts
server/routes/activities/create-an-activity/handlers/sessionTimesOption.test.ts
server/routes/activities/create-an-activity/handlers/sessionTimesOption.ts
server/views/pages/activities/create-an-activity/check-answers.njk

Various journey fixes during create activity

SAA-1981: Fix journey bugs for changing activity schedule during create

---

server/routes/activities/suspensions/handlers/viewAllocations.test.ts
server/routes/activities/suspensions/handlers/viewAllocations.ts
server/services/fixtures/activity_schedule_1.json
server/utils/helpers/activityTimeSlotMappers.test.ts
server/utils/helpers/activityTimeSlotMappers.ts
server/views/pages/activities/suspensions/view-allocations.njk

SAA-1946: Show activity session times in prisoners suspensions page

---

server/routes/activities/manage-activities/handlers/activity.test.ts
server/routes/activities/manage-activities/handlers/activity.ts
server/routes/activities/suspensions/handlers/viewAllocations.ts
server/utils/helpers/activityTimeSlotMappers.test.ts
server/utils/helpers/activityTimeSlotMappers.ts
server/views/pages/activities/manage-activities/view-activity.njk

Display session times on activity view page

SAA 1983 show schedule in view activity

---

server/routes/activities/manage-allocations/handlers/checkAnswers.test.ts
server/routes/activities/manage-allocations/handlers/checkAnswers.ts
server/routes/activities/manage-allocations/handlers/viewAllocation.test.ts
server/routes/activities/manage-allocations/handlers/viewAllocation.ts
server/views/pages/activities/manage-activities/view-activity.njk
server/views/pages/activities/manage-allocations/check-answers.njk
server/views/pages/activities/manage-allocations/confirm-exclusions.njk
server/views/pages/activities/manage-allocations/view-allocation.njk
server/views/pages/activities/suspensions/view-suspensions.njk

SAA-1947: Show times in allocation schedule

---

.circleci/config.yml
server/routes/activities/manage-allocations/handlers/confirmExclusions.test.ts
server/routes/activities/manage-allocations/handlers/confirmExclusions.ts
server/services/fixtures/activity_schedule_bi_weekly_1.json
server/utils/helpers/activityTimeSlotMappers.test.ts
server/utils/helpers/activityTimeSlotMappers.ts
server/views/pages/activities/manage-allocations/confirm-exclusions.njk

SAA-1964: Show schedule time in prisoner schedule - confirm exclusions

---

server/@types/bookAVideoLinkApi/types.ts
server/data/bookAVideoLinkApiClient.test.ts
server/data/bookAVideoLinkApiClient.ts
server/routes/appointments/video-link-booking/amendRoutes.ts
server/routes/appointments/video-link-booking/cancelRoutes.ts
server/routes/appointments/video-link-booking/handlers/cancelConfirmed.test.ts
server/routes/appointments/video-link-booking/handlers/cancelConfirmed.ts
server/routes/appointments/video-link-booking/handlers/confirmCancel.test.ts
server/routes/appointments/video-link-booking/handlers/confirmCancel.ts
server/routes/appointments/video-link-booking/index.ts
server/services/bookAVideoLinkService.test.ts
server/services/bookAVideoLinkService.ts
server/views/pages/appointments/video-link-booking/booking-cancelled.njk
server/views/pages/appointments/video-link-booking/confirm-cancel.njk
server/views/pages/appointments/video-link-booking/details.njk

BAVL-305: Cancel a video booking

---

server/routes/reporting/index.ts

Test locally by pointing and DPR tooling API

SAA-2007: Use new DPR waitlist definition

---

package-lock.json
package.json

Failure in the hmpps/trivy_latest_scan

SAA-2020: update body-parser-version 

---

server/data/bookAVideoLinkApiClient.test.ts
server/data/bookAVideoLinkApiClient.ts
server/routes/appointments/video-link-booking/amendRoutes.ts
server/routes/appointments/video-link-booking/createRoutes.ts
server/routes/appointments/video-link-booking/handlers/courtHearingLink.test.ts
server/routes/appointments/video-link-booking/handlers/courtHearingLink.ts
server/routes/appointments/video-link-booking/handlers/schedule.test.ts
server/routes/appointments/video-link-booking/handlers/schedule.ts
server/views/pages/appointments/video-link-booking/check-booking.njk
server/views/pages/appointments/video-link-booking/court-hearing-link.njk
server/views/pages/appointments/video-link-booking/details.njk

BAVL-337: Add CVP link to video bookings and allow bookings in any appointment room

---

server/routes/activities/create-an-activity/handlers/sessionTimes.test.ts
server/routes/activities/create-an-activity/handlers/sessionTimes.ts
server/views/pages/activities/create-an-activity/session-times.njk

*Bug fix week Tag
*Content update
*Widen gov container to create consistent times form box layout

SAA-2023: Bug and content refactoring on session times page

---

package-lock.json
package.json
server/views/pages/activities/manage-activities/view-activity.njk
server/views/pages/appointments/appointment-set/details.njk
server/views/pages/appointments/appointment/attendance.njk
server/views/pages/appointments/appointment/details.njk
server/views/pages/appointments/create-and-edit/check-answers.njk
server/views/pages/appointments/create-and-edit/schedule.njk
server/views/pages/appointments/partials/appointment-movement-slip.njk
server/views/pages/appointments/search/results.njk
server/views/partials/appointments/location-text.njk
server/views/partials/showLocation.njk
server/views/partials/showUnlockEvents.njk

Re-factored more places to use the new macro.

SAA-2004: Refactor to use new location macro

---

package-lock.json
package.json

Reverts ministryofjustice/hmpps-activities-management#1080

Revert "Update dependency date-fns to v4"

---

integration_tests/e2e/activities/attendance/activitiesAttendance.cy.ts
integration_tests/pages/activities/attendanceSummary/attendance.ts
server/routes/activities/daily-attendance-summary/handlers/attendance.test.ts
server/routes/activities/daily-attendance-summary/handlers/attendance.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/views/pages/activities/daily-attendance-summary/attendances.njk

SAA-1965: Show session times under the activity name on absences page

---

integration_tests/e2e/activities/attendance/activitiesAttendance.cy.ts
integration_tests/fixtures/activitiesApi/getAllAttendances.json
integration_tests/pages/activities/attendanceSummary/attendance.ts
server/@types/activitiesAPI/index.d.ts
server/routes/activities/daily-attendance-summary/handlers/attendance.test.ts
server/routes/activities/daily-attendance-summary/handlers/attendance.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/views/pages/activities/daily-attendance-summary/attendances.njk

SAA-1966: Tier 1 and Tier 2 - display session times

---

server/views/pages/appointments/attendance/summaries.njk

SAA-2026: Use macro to display in cell if present

---

server/routes/activities/manage-allocations/handlers/exclusions.test.ts
server/routes/activities/manage-allocations/handlers/exclusions.ts
server/views/pages/activities/manage-allocations/exclusions.njk

Reverts ministryofjustice/hmpps-activities-management#1086

Revert "SAA-2031 remove exclusions disabled logic"

---

server/views/pages/appointments/create-and-edit/appointment-set/extra-information.njk
server/views/pages/appointments/create-and-edit/extra-information.njk

SAA-1320: Content change

---

server/views/pages/activities/unlock-list/select-date-and-location.njk

Other AC on the ticket wasn't relevant as the link has already been removed

SAA-981: Add caption

---

server/views/pages/activities/manage-allocations/end-date.njk

SAA-2054: Use safe to escape encoded chars

---

frontend/utilities/_misc.scss

SAA-2057: Add margin to datepicker when inside filter bar

---

integration_tests/e2e/activities/attendance/attendanceNotRequired.cy.ts
integration_tests/e2e/activities/attendance/multipleActivities.cy.ts
integration_tests/e2e/activities/attendance/recordAttendance.cy.ts
integration_tests/fixtures/activitiesApi/getScheduledEventsMdi20230202.json
integration_tests/pages/recordAttendance/attendanceList.ts
integration_tests/pages/recordAttendance/attendanceListMultiple.ts
server/@types/activitiesAPI/index.d.ts
server/routes/activities/record-attendance/handlers/attendanceList.test.ts
server/utils/applyCancellationDisplayRule.test.ts
server/views/partials/attendance/otherEvent.njk

SAA-1822: Show attendance details for clashing events on attendance list

---

server/views/pages/activities/record-attendance/reset-attendance.njk

SAA-982: Add caption (missed AC)

---

helm_deploy/hmpps-activities-management/Chart.yaml
server/routes/activities/manage-allocations/handlers/confirmExclusions.ts
server/utils/helpers/activityTimeSlotMappers.test.ts
server/utils/helpers/activityTimeSlotMappers.ts

Also merged before updating the allocation

SAA-2066: fix for exlusions. Fix to calculate the added slots and removed exclusions

---

frontend/utilities/_misc.scss

Reverts ministryofjustice/hmpps-activities-management#1116

Revert "SAA-2057: Add margin to datepicker when inside filter bar"

---

server/views/pages/activities/suspensions/suspend-from.njk

Reverts ministryofjustice/hmpps-activities-management#1121

Revert "SAA-2071: Fix datepicker import error"

---

server/views/pages/activities/suspensions/suspend-from.njk

Reverts ministryofjustice/hmpps-activities-management#1125

Revert "Revert "SAA-2071: Fix datepicker import error""

---

frontend/utilities/_misc.scss

Reverts ministryofjustice/hmpps-activities-management#1124

Revert "Revert "SAA-2057: Add margin to datepicker when inside filter bar""

---

server/config.ts
server/nunjucks/nunjucksSetup.ts

Reverts ministryofjustice/hmpps-activities-management#1123

Revert "Reset prod static cache duration to zero"

---

integration_tests/e2e/activities/nonAssociations.cy.ts
server/routes/activities/non-associations/handlers/nonAssociations.test.ts
server/routes/activities/non-associations/handlers/nonAssociations.ts
server/views/partials/activities/nonAssociationsTable.njk

SAA-2124: Show location of allocation on non-associations page

---

integration_tests/e2e/appointments/createAppointment.cy.ts
integration_tests/e2e/appointments/reviewNonAssociationsPage.cy.ts
integration_tests/pages/appointments/create-and-edit/confirmNonAssociationsPage.ts
server/routes/appointments/create-and-edit/createRoutes.ts
server/routes/appointments/create-and-edit/handlers/confirm-non-associations.ts
server/routes/appointments/create-and-edit/handlers/confirmNonAssociations.test.ts
server/routes/appointments/create-and-edit/handlers/confirmNonAssociations.ts.ts
server/routes/appointments/create-and-edit/handlers/reviewNonAssociations.test.ts
server/routes/appointments/create-and-edit/handlers/reviewNonAssociations.ts
server/services/index.ts
server/services/nonAssociationsService.test.ts
server/services/nonAssociationsService.ts
server/views/pages/appointments/create-and-edit/confirm-non-associations.njk
server/views/pages/appointments/create-and-edit/review-non-associations.njk

SAA-2006: Confirm any remaining non-associations

---

server/routes/activities/unlock-list/handlers/applyFilters.ts
server/routes/activities/unlock-list/handlers/plannedEvents.test.ts
server/routes/activities/unlock-list/handlers/plannedEvents.ts
server/routes/activities/unlock-list/journey.ts
server/services/unlockListService.test.ts
server/services/unlockListService.ts
server/views/pages/activities/unlock-list/planned-events.njk
server/views/partials/activities/unlock-list/filterSections/cancelledEvents.njk

SAA-2204: Filter cancelled events

---

server/views/pages/activities/suspensions/view-suspensions.njk

SAA-2196: Suspensions details page update

---

integration_tests/e2e/activities/changesInCircumstances.cy.ts
integration_tests/fixtures/activitiesApi/getChangeEvents.json
server/views/pages/activities/change-of-circumstances/view-events.njk

SAA-2242: Fix blank cell moves in change of circumstances

---

integration_tests/e2e/activities/suspensions.cy.ts
server/routes/activities/suspensions/handlers/viewAllocations.test.ts
server/routes/activities/suspensions/handlers/viewAllocations.ts
server/views/pages/activities/suspensions/view-allocations.njk

SAA-2190: Unpaid activity display as unpaid even if suspended alongside paid suspensions

---

helm_deploy/hmpps-activities-management/values.yaml

Reverts ministryofjustice/hmpps-activities-management#1305

Revert "SAA-2265: update the client_max_body_size in the ingress controller"

---

server/routes/appointments/attendance/handlers/summaries.test.ts
server/routes/appointments/attendance/handlers/summaries.ts
server/routes/appointments/attendance/index.ts
server/views/pages/appointments/attendance/summaries-multi-select.njk

SAA-2197: Add search bar for appointments

---

server/views/pages/activities/allocation-dashboard/activities.njk

I have tested with Dev data. Case sensitivity and number now sort correctly on the Activity column within the Allocations Dashboard

SAA-2262: Bug Activities sort on Allocations Dashboard

---

server/views/pages/activities/record-attendance/attendance-list-multiple.njk
server/views/pages/activities/record-attendance/attendance-list-single.njk

SAA-1800: add an incentive level waring to the attendance list

---

server/routes/appointments/attendance/handlers/attendees.test.ts
server/routes/appointments/attendance/handlers/attendees.ts
server/routes/appointments/attendance/handlers/summaries.test.ts
server/routes/appointments/attendance/handlers/summaries.ts
server/routes/appointments/attendance/index.ts
server/routes/appointments/utils/attendanceUtils.ts
server/views/pages/appointments/attendance/attendees.njk

SAA-2197: Add clashes column to attendees view

---

helm_deploy/values-dev.yaml
server/routes/appointments/attendance/handlers/attendees.test.ts
server/routes/appointments/attendance/handlers/attendees.ts
server/routes/appointments/attendance/handlers/summaries.test.ts
server/routes/appointments/attendance/index.ts
server/routes/appointments/utils/attendanceUtils.ts
server/views/pages/appointments/attendance/attendees.njk
server/views/pages/appointments/attendance/summaries-multi-select.njk

SAA-2197: Add search bar to attendees

---

server/views/pages/activities/manage-allocations/exclusions.njk

SAA-1924: Content change in caption and h1

---

package-lock.json
package.json

updated dependency to fix https://github.com/advisories/GHSA-c76h-2ccp-4975

fix npm security alert

---

server/views/partials/activities/allocation-dashboard/waitlistHtml.njk

also updated dropdown to use existing enum

SAA-2337 updated waitlist tab status filter text

---

package-lock.json
package.json

https://github.com/advisories/GHSA-76p7-773f-r4q5

update security alerted dependency

---

server/views/pages/activities/record-attendance/attendance-list-multiple.njk

SAA-2377: Change loading spinner content

---

server/services/locationsService.test.ts
server/services/locationsService.ts

SAA-2375: Sort locations alphabetically in activity create / update

---

server/routes/activities/administration/handlers/updatePrisonPayBand.test.ts
server/routes/activities/administration/handlers/updatePrisonPayBand.ts
server/views/pages/activities/administration/update-prison-pay-band.njk

SAA-2392 prevent editing of the nomis pay band id when updating a prison pay band

---

server/routes/appointments/create-and-edit/handlers/name.test.ts
server/routes/appointments/create-and-edit/handlers/name.ts
server/routes/appointments/video-link-booking/court/handlers/dateAndTime.test.ts
server/routes/appointments/video-link-booking/court/handlers/dateAndTime.ts
server/routes/appointments/video-link-booking/court/handlers/hearingDetails.test.ts
server/routes/appointments/video-link-booking/court/handlers/hearingDetails.ts
server/routes/appointments/video-link-booking/probation/createRoutes.ts
server/routes/appointments/video-link-booking/probation/handlers/checkBooking.test.ts
server/routes/appointments/video-link-booking/probation/handlers/checkBooking.ts
server/routes/appointments/video-link-booking/probation/handlers/confirmation.test.ts
server/routes/appointments/video-link-booking/probation/handlers/confirmation.ts
server/routes/appointments/video-link-booking/probation/handlers/dateAndTime.test.ts
server/routes/appointments/video-link-booking/probation/handlers/dateAndTime.ts
server/routes/appointments/video-link-booking/probation/handlers/extraInformation.test.ts
server/routes/appointments/video-link-booking/probation/handlers/extraInformation.ts
server/routes/appointments/video-link-booking/probation/handlers/location.test.ts
server/routes/appointments/video-link-booking/probation/handlers/location.ts
server/routes/appointments/video-link-booking/probation/handlers/meetingDetails.test.ts
server/routes/appointments/video-link-booking/probation/handlers/meetingDetails.ts
server/routes/appointments/video-link-booking/probation/handlers/schedule.test.ts
server/routes/appointments/video-link-booking/probation/handlers/schedule.ts
server/routes/appointments/video-link-booking/probation/handlers/selectPrisoner.test.ts
server/routes/appointments/video-link-booking/probation/handlers/selectPrisoner.ts
server/routes/appointments/video-link-booking/probation/index.ts
server/views/pages/appointments/video-link-booking/court/hearing-details.njk
server/views/pages/appointments/video-link-booking/probation/check-booking.njk
server/views/pages/appointments/video-link-booking/probation/confirmation.njk
server/views/pages/appointments/video-link-booking/probation/meeting-details.njk
server/views/pages/appointments/video-link-booking/probation/select-prisoner.njk

BAVL-644: Probation video booking create journey

---

server/routes/activities/manage-allocations/createRoutes.ts
server/routes/activities/manage-allocations/handlers/allocateMultiplePeople/activityRequirementsReview.ts
server/routes/activities/manage-allocations/handlers/allocateMultiplePeople/reviewUploadPrisonerList.ts
server/routes/activities/manage-allocations/handlers/allocateMultiplePeople/uploadPrisonerList.test.ts
server/routes/activities/manage-allocations/handlers/allocateMultiplePeople/uploadPrisonerList.ts
server/routes/activities/manage-allocations/journey.ts
server/utils/helpers/allocationUtil.test.ts
server/utils/helpers/allocationUtil.ts
server/views/pages/activities/manage-allocations/allocateMultiplePeople/reviewUploadPrisonerList.njk

Saa 2367: csv upload. Add look ups to route for current allocation and incentive levels

---

package-lock.json
package.json

trying to fix security alert: https://github.com/advisories/GHSA-968p-4wvh-cqc8

update babel dependency packages

---

integration_tests/e2e/activities/allocations/allocationsStubHelper.ts
server/routes/activities/manage-allocations/handlers/endDate.test.ts
server/routes/activities/manage-allocations/handlers/endDate.ts
server/routes/activities/manage-allocations/handlers/endDateOption.test.ts
server/routes/activities/manage-allocations/handlers/endDateOption.ts

Make sure the paid variable is correct in schedule stub and add in correct redirect

SAA-2456: Correct activity stub for the right redirect

---

server/utils/editAppointmentUtils.test.ts
server/utils/editAppointmentUtils.ts

Content changes for cancelling, uncancelling and deleting appointments

SAA-1956: Content changes for cancelling, uncancelling and deleting appointments

---

integration_tests/e2e/activities/attendance/uncancelMultipleSessions.cy.ts
server/routes/activities/record-attendance/handlers/activities.test.ts
server/routes/activities/record-attendance/handlers/activities.ts
server/routes/activities/record-attendance/handlers/uncancel-multiple-sessions/confirmation.test.ts
server/routes/activities/record-attendance/handlers/uncancel-multiple-sessions/confirmation.ts
server/views/pages/activities/record-attendance/activities.njk
server/views/pages/activities/record-attendance/cancel-multiple-sessions/payment.njk
server/views/partials/attendance/activitiesTable.njk

Includes: 
https://dsdmoj.atlassian.net/browse/SAA-2504 
https://dsdmoj.atlassian.net/browse/SAA-2505
Also removed pagination from uncancel activities list page

Cancel and uncancel multiple sessions updates

---

server/routes/activities/record-attendance/handlers/activities.test.ts
server/routes/activities/record-attendance/handlers/activities.ts
server/routes/activities/record-attendance/handlers/uncancel-multiple-sessions/activitiesList.test.ts
server/routes/activities/record-attendance/handlers/uncancel-multiple-sessions/activitiesList.ts
server/routes/appointments/attendance-summary-stats/handlers/attendanceData.test.ts
server/routes/appointments/attendance-summary-stats/handlers/attendanceData.ts
server/routes/appointments/attendance/handlers/attendees.test.ts
server/routes/appointments/attendance/handlers/attendees.ts
server/routes/appointments/attendance/handlers/summaries.test.ts
server/routes/appointments/attendance/handlers/summaries.ts
server/views/pages/activities/record-attendance/activities.njk
server/views/pages/activities/record-attendance/uncancel-multiple-sessions/cancelled-activities.njk

SAA-3416: Code changes to allow ampersand symbol in search filters

---

server/utils/helpers/activityDateValidator.test.ts
server/utils/helpers/activityDateValidator.ts

SAA-3626: Update End date when there is no schedule in week two
