helm_deploy/hmpps-activities-management/values.yaml
Certificate secret name was incorrect from template - did not match the CP name. This corrects it.
=> SAA-33: Correct cert secret name

helm_deploy/values-dev.yaml
Oops. Added two env vars to the config.ts file but forgot to set these in /helm_deploy/values-dev.yaml. This corrects the omission.
=> SAA-15: Provide missing env vars for API urls

package-lock.json, package.json
Small change to update typescript version 4.8.2 -> 4.8.3 (Fixes overnight security check in circleci too)
=> SAA-14: Update dependencies

.circleci/config.yml, Dockerfile, README.md, package-lock.json, package.json
This brings inline with the latest TypeScript template.
=> SAA-134 updating front end to latest LTS version of Node, v18.

.circleci/config.yml, helm_deploy/hmpps-activities-management/Chart.yaml
- Hoping upgrading the circle orb will help speed up the multi-architecture builds
=> ⬆️ SAA-154: Upgrade Circle Orb to v6 and Helm charts to 2.1.0

server/@types/activitiesAPI/index.d.ts
This is related to this [pull request](https://github.com/ministryofjustice/hmpps-activities-management-api/pull/73)
=> SAA-178 regenerating the activity api types on the back of a conctract change to activites and allocations.

server/routes/allocate-to-activity/candidates/people-allocated-now/handlers/PeopleAllocatedNowRouteHandler.test.ts, server/routes/allocate-to-activity/candidates/people-allocated-now/handlers/PeopleAllocatedNowRouteHandler.ts, server/views/pages/allocate-to-activity/candidates/people-allocated-now/index.njk
This isn't quite as per ticket for the allocation column.  It should show all schedules they are allocated to.  We currently don't have an endpoint to support this.
=> SAA-211 adding missing description text and populating the allocation column.

server/@types/activities.ts, server/@types/activitiesAPI/index.d.ts, server/data/activitiesApiClient.test.ts, server/data/activitiesApiClient.ts, server/routes/spikes/handlers/calendarSpike.ts, server/services/unlockListService.test.ts, server/services/unlockListService.ts, server/views/partials/showUnlockEvents.njk
With the API changes to get scheduled events from a view, these are the minor changes required in the UI to match up.
=> SAA-256: Use new API endpoints in unlock list and calendar spike

frontend/utilities/_typography.scss, server/views/pages/allocate-to-activity/check-answers.njk, server/views/pages/appointments/create-single/check-answers.njk, server/views/pages/create-an-activity/check-answers.njk, server/views/pages/manage-schedules/create-schedule/check-answers.njk
Removed grey summary list heading from check answers pages
=> SAA-458: Remove grey summary list heading

integration_tests/e2e/appointments/createGroupAppointment.cy.ts, integration_tests/fixtures/prisonerSearchApi/getPrisonPrisoners-MDI-A1351DZ.json, integration_tests/pages/appointments/create/checkAnswersPage.ts, integration_tests/pages/appointments/create/reviewPrisonersPage.ts, integration_tests/pages/page.ts, server/middleware/setUpChangeLinks.ts, server/nunjucks/nunjucksSetup.ts, server/routes/appointments/create/handlers/reviewPrisoners.test.ts, server/routes/appointments/create/handlers/reviewPrisoners.ts, server/routes/create-an-activity/handlers/checkEducationLevels.test.ts, server/routes/create-an-activity/handlers/checkEducationLevels.ts, server/routes/create-an-activity/handlers/checkPay.test.ts, server/routes/create-an-activity/handlers/checkPay.ts, server/routes/create-an-activity/journey.ts, server/views/pages/appointments/create/check-answers.njk, server/views/pages/appointments/create/check-answers.njk.test.ts, server/views/pages/appointments/create/confirmation.njk, server/views/pages/appointments/create/confirmation.njk.test.ts, server/views/pages/appointments/create/repeat-period-and-count.njk.test.ts, server/views/pages/appointments/create/repeat.njk.test.ts, server/views/pages/appointments/create/review-prisoners.njk, server/views/partials/showProfileLink.njk
- Updated check answers page to support editing prisoner list.
- Added tests 
Note: To support the multi-page change prisoners flow, I've changed the way the check answers `from-review` param works. Now this param will set a session which will be used by the `redirectOrReturn` method to return to check answers page.
=> SAA-467: Updated check answers page for group appointments

server.ts, server/utils/azureAppInsights.ts
Discovered that the UI service has not been logging traces or exceptions to App Insights (for some time..)
This config change should instrument Bunyan to do this.
Test (for last 3 days)
```
traces
| where cloud_Rolename == 'hmpps-activities-management'
```
=> SAA-742: Small changes to app insights configuration.

frontend/components/multi-select/multi-select.js, server/views/components/multi-select.njk, server/views/pages/allocation-dashboard/allocation-dashboard.njk
Adds an edit allocation button to the "current allocated" tab of the allocation dashboard.
Note: Edit functionality to come in later ticket
=> SAA-715: Adds "edit allocation" button

frontend/components/tags/_tags.scss, server/@types/activitiesAPI/index.d.ts, server/services/unlockListService.ts, server/views/pages/record-attendance/attendance-list.njk, server/views/pages/record-attendance/not-attended-reason.njk, server/views/partials/attendance/otherEvent.njk, server/views/partials/showUnlockEvents.njk
When set shows the appointment description on the unlock list and orders events by start time, summary.
Note: I've included a content change for events on the "attendance list" and "not attended reason" page. This is to support the change to the appointment summary field (https://github.com/ministryofjustice/hmpps-activities-management-api/pull/350) and brings the design in line with the latest version of the prototype.
=> SAA-607: Updated unlock list appointment events

frontend/utilities/_misc.scss, integration_tests/e2e/appointments/editAppointments.cy.ts, integration_tests/pages/appointments/create-and-edit/checkAnswersPage.ts, integration_tests/pages/appointments/movementSlip/occurrenceMovementSlip.ts, server/routes/appointments/create-and-edit/bulkAppointmentJourney.ts, server/routes/appointments/create-and-edit/createRoutes.ts, server/routes/appointments/create-and-edit/handlers/bulk-appointments/bulkAppointmentAddComment.test.ts, server/routes/appointments/create-and-edit/handlers/bulk-appointments/bulkAppointmentAddComment.ts, server/routes/appointments/create-and-edit/handlers/bulk-appointments/bulkAppointmentComments.test.ts, server/routes/appointments/create-and-edit/handlers/bulk-appointments/bulkAppointmentComments.ts, server/routes/appointments/create-and-edit/handlers/bulk-appointments/reviewBulkAppointment.test.ts, server/routes/appointments/create-and-edit/handlers/bulk-appointments/reviewBulkAppointment.ts, server/routes/appointments/create-and-edit/handlers/checkAnswers.ts, server/services/editAppointmentService.test.ts, server/utils/editAppointmentUtils.test.ts, server/utils/editAppointmentUtils.ts, server/views/pages/appointments/create-and-edit/bulk-appointments/add-comment.njk, server/views/pages/appointments/create-and-edit/bulk-appointments/add-comment.njk.test.ts, server/views/pages/appointments/create-and-edit/bulk-appointments/bulk-appointment-comments.njk, server/views/pages/appointments/create-and-edit/bulk-appointments/bulk-appointment-comments.njk.test.ts, server/views/pages/appointments/create-and-edit/category.njk, server/views/pages/appointments/create-and-edit/category.njk.test.ts, server/views/pages/appointments/create-and-edit/check-answers.njk, server/views/pages/appointments/create-and-edit/comment.njk, server/views/pages/appointments/create-and-edit/comment.njk.test.ts, server/views/pages/appointments/movement-slip/occurrence.njk.test.ts, server/views/pages/appointments/occurrence-details/occurrence.njk, server/views/pages/appointments/partials/occurrence-movement-slip.njk
This change primarily adds support for bulk appointment comments via two new pages in the bulk appointment journey (screenshots below).
There are also a few minor fixes and content changes included with this PR:
- Fix to escape comments containing HTML on the movement slip, check answers and occurrence details pages
- Fixed back button href on the category page
- Renames all old "heads up" references to "extra information" (screenshots out of date)
=> SAA-731: Bulk appointment comments

server/services/unlockListService.ts, server/utils/editAppointmentUtils.test.ts, server/utils/editAppointmentUtils.ts, server/views/pages/unlock-list/planned-events.njk, server/views/partials/showUnlockEvents.njk
Adds "extra information" tag to appointments with comments.
I've also included fixes to correct the prisoner name formatting on the unlock list and fixed the bug preventing appointment comments being removed in the edit journey.
=> SAA-752: Unlock list appointment event updates

frontend/utilities/_all.scss, frontend/utilities/_print.scss, frontend/utilities/_typography.scss, server/views/pages/unlock-list/planned-events.njk, server/views/partials/showProfileLink.njk, server/views/partials/showUnlockEvents.njk
- Removes width token to prevent 100% table column width on mobile viewports.
- Adds styling improvements for small print viewports
**Before**
**After**
=> SAA-752: Bug fix & unlock list print improvements

frontend/utilities/_print.scss, frontend/utilities/_typography.scss, server/@types/activities.ts, server/routes/activities/unlock-list/handlers/plannedEvents.test.ts, server/routes/activities/unlock-list/handlers/plannedEvents.ts, server/services/unlockListService.test.ts, server/services/unlockListService.ts, server/views/pages/activities/unlock-list/planned-events.njk
Some minor content changes to the printed unlock list.
I'm very uncomfortable with wrapping the content in a table for a printable footer but this seems to be the only way to do it?
I also don't like forcing the notes to be right positioned since it will be squashed at smaller printable viewports (A5 portrait), but since that combination seems unlikely from UR I've removed the responsive styling from the printable grid layout.
=> SAA-574: Unlock list updates

server/routes/appointments/create-and-edit/handlers/bulk-appointments/uploadBulkAppointment.test.ts, server/routes/appointments/create-and-edit/handlers/uploadPrisonerList.test.ts, server/validators/isValidCsvFile.test.ts, server/validators/isValidCsvFile.ts
The pen testing process uncovered an as yet unidentified way of getting a valid CSV file to report with an Excel mime type. The existing validation expects the file to be uploaded with mime type text/csv.
Mime types are easily spoofed and the CSV validation checker also applies the more rigorous isBinaryFile check. This more effective check makes the mime type check redundant.
Resolution of this bug is to remove the mime type check.
=> SAA-1056: Remove CSV mime type test to support browsers that send incorrect mime type

server/routes/activities/allocation-dashboard/handlers/startDate.test.ts, server/routes/activities/allocation-dashboard/handlers/startDate.ts, server/validators/dateIsSameOrBefore.test.ts, server/validators/dateIsSameOrBefore.ts
=> SAA-1039 validating allocation start date on edit allocation  against the activity end date (if the activity has one).

server/routes/appointments/create-and-edit/handlers/repeatPeriodAndCount.test.ts, server/routes/appointments/create-and-edit/handlers/repeatPeriodAndCount.ts
Adds validation to the "How often will the appointment repeat?" page, limiting the number of repeats that can be entered to prevent creation of extremely large appointments.
=> SAA-997: Limit appointment occurrence allocations

server/routes/activities/manage-schedules/handlers/activities.test.ts, server/routes/activities/manage-schedules/handlers/activities.ts, server/views/pages/activities/manage-schedules/activities-dashboard.njk
Moves the filter menu on the activities dashboard to the side and removes category filter
=> SAA-924: Activities dashboard updates

server/routes/activities/create-an-activity/handlers/pay.test.ts, server/routes/activities/create-an-activity/handlers/pay.ts, server/routes/activities/create-an-activity/handlers/payRateType.test.ts, server/routes/activities/create-an-activity/handlers/payRateType.ts, server/routes/activities/create-an-activity/handlers/removePay.test.ts, server/routes/activities/create-an-activity/handlers/removePay.ts, server/routes/activities/create-an-activity/index.ts, server/routes/activities/manage-schedules/handlers/checkPay.test.ts, server/routes/activities/manage-schedules/handlers/checkPay.ts, server/routes/activities/manage-schedules/index.ts, server/views/pages/activities/create-an-activity/check-pay.njk, server/views/pages/activities/manage-schedules/check-pay.njk
Updates the edit pay journey to save updated pay rates immediately when creating, editing or deleting pay. This removes the need to "confirm" changes from the check pay page.
=> SAA-1037: Updated edit pay journey

server/routes/activities/create-an-activity/handlers/checkAnswers.ts, server/services/fixtures/activity_1.json
Fixes the start allocating link below:
=> SAA-1177 check answers was passing through the schedule id when it should be the activity id.

server/views/pages/activities/create-an-activity/pay.njk
Fixes the back link on the enter pay screen
=> SAA-1179 fixing the back link on the create activites enter pay screen.

server/routes/activities/create-an-activity/handlers/endDate.test.ts, server/routes/activities/create-an-activity/handlers/endDate.ts, server/routes/activities/create-an-activity/journey.ts, server/routes/activities/manage-schedules/handlers/activity.test.ts, server/routes/activities/manage-schedules/handlers/activity.ts
When editing an activity end date from this page, getting 404.  This was because behind the scenes it is looking up the activity schedule using the activity id.
=> SAA-1193 resolving issue where we are using the activity id to look up a schedule when trying edit the end date of an activity.

server/routes/activities/create-an-activity/handlers/startDate.test.ts, server/routes/activities/create-an-activity/handlers/startDate.ts
When editing an activity start date from this page, getting 404. This was because behind the scenes it is looking up the activity schedule using the activity id.
=> SAA-1197 resolving issue where we are using the activity id to look up a schedule when trying edit the start date of an activity.

package.json, server/config.ts, server/routes/appointments/create-and-edit/handlers/repeatFrequencyAndCount.test.ts, server/routes/appointments/create-and-edit/handlers/repeatFrequencyAndCount.ts, server/services/editAppointmentService.test.ts, server/services/editAppointmentService.ts, server/utils/editAppointmentUtils.ts
Adds validation to prevent creating a large number of new appointment instances when adding prisoners to an appointment.
=> SAA-1085: Max appointment instances validation

server/middleware/activities/initialiseEditJourney.test.ts, server/middleware/activities/initialiseEditJourney.ts, server/routes/activities/create-an-activity/handlers/endDate.test.ts, server/routes/activities/create-an-activity/handlers/endDate.ts, server/views/pages/activities/create-an-activity/end-date.njk
This adds extra activity end date validation to ensure end date is always set to a date in the future (also needs API validation).
I've also added support for the `latestAllocationStartDate` and `earliestAllocationStartDate` journey properties to the initialise `initialiseEditJourney` middleware. I added this originally, but I think it may have been removed when resolving merge conflicts.
=> SAA-1296: Bug fixes

server/views/pages/activities/create-an-activity/check-answers.njk
Small bug fix for missing flat pay alias on the check answers page.
**Before**
**After**
=> SAA-1332: Fix for missing flat pay alias

server/routes/appointments/create-and-edit/handlers/schedule.test.ts, server/routes/appointments/create-and-edit/handlers/schedule.ts
**Issue:** : Page link not pointing to appointment details, instead point to main page. appointmentId is not passed.  
**Resolved** adjudicationId passed from ts file to njk render.
=> SAA-1218 appointmentId passed to njk for the url

server/utils/azureAppInsights.ts
This PR adds username and their active caseload as custom dimensions for Requests.
It has been requested by the team who monitor the unique user counts for DPS v. NOMIS usage.
To test, our service should start to appear in this app insights query:
`requests
| mv-expand prison = split(customDimensions.activeCaseLoadId, ",") to typeof(string) 
| extend username = tostring(customDimensions.username)
| extend role_name = tostring(cloud_RoleName)
| where customDimensions.activeCaseLoadId <> ""
| where success == 'True'
//| where timestamp between(dateStart .. dateEnd)
| summarize totalRequests=count(), Distinct_Users=dcount(username) 
by 
format_datetime(timestamp, 'yyyy-MM'), 
establishment = trim(@"[^\w]+",prison),
role_name`
Where it does not currently appear.
Risk: LOW  - but needs to be …
=> SAA-1348 add custom dimensions to requests for app insights metrics

server/@types/activitiesAPI/index.d.ts, server/routes/appointments/attendance/handlers/summaries.test.ts, server/routes/appointments/attendance/handlers/summaries.ts, server/routes/appointments/attendance/index.ts, server/views/pages/appointments/attendance/summaries.njk
Change:
Record Maintanance Page to display single prision information.
Before Changes:
Appointment Canteen, has only 1 Attendee but it shows a number. 
After Changes:
Appointment Canteen, Shows the Prisoner details.
=> SAA-1314 Single Attendee information added

integration_tests/e2e/appointments/createGroupAppointment.cy.ts, integration_tests/e2e/appointments/createGroupRepeatAppointment.cy.ts, integration_tests/e2e/appointments/createIndividualAppointment.cy.ts, integration_tests/e2e/appointments/createIndividualAppointmentBackLinks.cy.ts, integration_tests/e2e/appointments/createIndividualAppointmentCheckAnswers.cy.ts, integration_tests/e2e/appointments/createIndividualRepeatAppointment.cy.ts, integration_tests/pages/appointments/create-and-edit/checkAnswersPage.ts, integration_tests/pages/appointments/create-and-edit/hostPage.ts, integration_tests/pages/appointments/create-and-edit/tierPage.ts, server/@types/activitiesAPI/index.d.ts, server/routes/appointments/create-and-edit/appointmentJourney.ts, server/routes/appointments/create-and-edit/createRoutes.ts, server/routes/appointments/create-and-edit/handlers/checkAnswers.test.ts, server/routes/appointments/create-and-edit/handlers/checkAnswers.ts, server/routes/appointments/create-and-edit/handlers/host.test.ts, server/routes/appointments/create-and-edit/handlers/host.ts, server/routes/appointments/create-and-edit/handlers/name.test.ts, server/routes/appointments/create-and-edit/handlers/name.ts, server/routes/appointments/create-and-edit/handlers/tier.test.ts, server/routes/appointments/create-and-edit/handlers/tier.ts, server/views/pages/appointments/create-and-edit/check-answers.njk, server/views/pages/appointments/create-and-edit/check-answers.njk.test.ts, server/views/pages/appointments/create-and-edit/host.njk, server/views/pages/appointments/create-and-edit/tier.njk
Adds tiers and organisers to appointment journeys (group and bulk). Edit appointment and updates to appointment details page to come in next PR.
=> SAA-1173: Appointment tiers & hosts (create journey)

server/views/pages/appointments/appointment/details.njk
Bug fix to remove change links for tier and host when appointment has been canceled or has expired
=> SAA-1181: Remove change link for past appointments

server/routes/activities/manage-allocations/handlers/confirmExclusions.test.ts, server/routes/activities/manage-allocations/handlers/confirmExclusions.ts, server/routes/activities/manage-allocations/handlers/exclusions.test.ts, server/routes/activities/manage-allocations/handlers/exclusions.ts, server/utils/helpers/activityTimeSlotMappers.test.ts, server/utils/helpers/activityTimeSlotMappers.ts, server/views/pages/activities/manage-allocations/confirm-exclusions.njk, server/views/pages/activities/manage-allocations/exclusions.njk
A few content changes:
- "Confirm exclusions" heading to "Check changes to when [First name Last name] should attend [Activity name]"
- Minor update to content of success messages. Now, "You’ve changed when [First name Last name] should attend [Activity name]"
- Made "Week 1" and "Week 2" headings on the exclusion checkbox selection page h2s, and moved to a basic columned layout for checkboxes.
=> SAA-1420: Exclusions content changes

server/views/pages/activities/waitlist-dashboard/dashboard.njk
Removes text around allocating from approved applications when user doesn't have `ACTIVITY_HUB` role.
=> SAA-1440: Waitlist dashboard content update

server/routes/activities/allocation-dashboard/handlers/allocationDashboard.ts
Quick fix to sort waitlist applications on the allocations dashboard.
**Before**
**After**
=> SAA-1458: Added sort to waitlist applications

integration_tests/pages/recordAttendance/activitiesPage.ts, server/views/pages/activities/record-attendance/activities.njk, server/views/pages/appointments/appointment-series/details.njk, server/views/pages/appointments/appointment/details.njk, server/views/pages/appointments/attendance/summaries.njk, server/views/partials/attendance/otherEvent.njk, server/views/partials/showUnlockEvents.njk
Some quick fixes for back links. Where we are unable to provide a workable backlink we open link in a new tab allowing user to close the tab and return to the previous screen.
=> SAA-1483: Back link quick fixes

server/routes/activities/manage-allocations/handlers/endDateOption.test.ts, server/routes/activities/manage-allocations/handlers/endDateOption.ts, server/routes/activities/record-attendance/handlers/removePay.test.ts
Bring error message inline with the content doc:
before:
after:
=> SAA-1120 very small content change to error message when saying if want to add an end date or not when allocating a prisoner.

server/views/pages/activities/change-of-circumstances/view-events.njk
Fixes styling of event tags on COC page
**Before**
**After**
=> SAA-1490: Fixed event tag styling on COC page

server/routes/activities/daily-attendance-summary/handlers/notAttendedSelectDate.test.ts, server/routes/activities/daily-attendance-summary/handlers/notAttendedSelectDate.ts
Issue: Activities - View people who are not attended yet 
Back button is not clearing the session and not loading the Categories and data correctly.
After: Session is set to null and categories are reloaded again.
=> SAA-1489 Back session set to null in POST method

server/routes/activities/manage-allocations/handlers/removeDateOption.test.ts, server/routes/activities/manage-allocations/handlers/removeDateOption.ts, server/routes/activities/manage-allocations/handlers/startDate.test.ts, server/routes/activities/manage-allocations/handlers/startDate.ts
Updated error messaging for validation in edit allocation journey for:
**Remove allocation validation**
**Start date allocation validation**
=> SAA-1118: Update validation error messages

server/views/pages/appointments/create-and-edit/apply-to.njk
Form Spinner: Edit Manage Appointment has when updating require Loading spinner.
Before: While updating and sync with no spinner is loaded.
After: Spinner added until the update is completed.
=> SAA-1092 Loading Spinner for appointments

server/views/pages/activities/manage-activities/view-activity.njk
Bug fix to remove activity tier and organiser change links when activity has ended.
**Before**
**After**
=> SAA-1517: Remove tier change link when activity has ended

integration_tests/e2e/allocateToActivity.cy.ts, integration_tests/e2e/deallocateFromActivity.cy.ts, server/data/activitiesApiClient.test.ts, server/data/activitiesApiClient.ts
This changes the API client to only use the filtered Activities endpoint due to the large volume of instances and attendances that are building up over time.
This is using the default API period of one month's recent instances.
=> SAA-1536 we should only use the filtered activities endpoint when retrieving activities to avoid pulling back too much (unused instances) data.

.circleci/config.yml, Dockerfile
SAA-1566: Update base image to bookworm to clear [CVE-2024-0567](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-activities-management/4037/workflows/9b1e0d0b-0ae1-4bf1-9726-01b5ec308c45/jobs/17175?invite=true#step-106-1312_147)
=> SAA-1566: Update base image to bookworm to fix CVE

server/routes/activities/waitlist-dashboard/handlers/dashboard.test.ts, server/views/pages/activities/waitlist-dashboard/dashboard.njk
Add earliestReleaseDate to the waitlist dashboard to replace the prisoner release date.
=> SAA-1571: Add earliestReleaseDate to the waitlist dashboard

gruntfile.js, integration_tests/e2e/appointments/manageAppointment.cy.ts, integration_tests/fixtures/activitiesApi/getAppointmentSearchResults.json, integration_tests/pages/appointments/appointment/appointmentsSearchResultsPage.ts, integration_tests/pages/appointments/appointment/searchSelectDatePage.ts, integration_tests/pages/appointments/appointmentsManagementPage.ts, server/views/pages/appointments/search/results.njk, server/views/pages/appointments/search/results.njk.test.ts, server/views/pages/appointments/search/select-date.njk, tsconfig.json
- Show in cell location in appointment search results table
- Configure `grunt` to only copy `.njk` files
- Configure `tsc` to exclude source maps
**NB: I'll double check the `grunt` and `tsc` changes once deployed to `dev`**
=> SAA-1614: Fix missing in cell location in appointments dashboard search results

server/routes/activities/record-attendance/handlers/attendanceList.test.ts, server/routes/activities/record-attendance/handlers/attendanceList.ts, server/views/pages/activities/record-attendance/not-attended-reason.njk
1. content needs a space around {time} to {time}. 
2.  Adjudication hearings should have been included, but they were added to the api after the UI was written, and as the UI also flattens the objects, it needs to be explicitly included
=> SAA-1593 fix content, add adjudication hearings

server/routes/appointments/create-and-edit/handlers/dateAndTime.test.ts, server/routes/appointments/create-and-edit/handlers/dateAndTime.ts
When the start date/time is changed on the confirm screen to be before the current time then skip the schedule clash screen
=> SAA-1656 Retrospective appointments. Change the start time to be in the past

integration_tests/e2e/appointments/createAppointment.cy.ts, integration_tests/e2e/appointments/createAppointmentCheckAnswers.cy.ts, integration_tests/e2e/appointments/createRepeatAppointment.cy.ts, integration_tests/e2e/appointments/createRetrospectiveAppointment.cy.ts, server/views/pages/appointments/create-and-edit/review-prisoners.njk, server/views/pages/appointments/create-and-edit/review-prisoners.njk.test.ts
Change to screen logic when adding people. Add an extra button to return directly to the select prisoner screen when adding an individual prisoner
Review
Add individual button
Add CSV button
=> SAA-1297: add multiple people to appointments

server/routes/appointments/create-and-edit/appointmentJourney.ts, server/routes/appointments/create-and-edit/createRoutes.ts, server/routes/appointments/create-and-edit/handlers/checkAnswers.test.ts, server/routes/appointments/create-and-edit/handlers/checkAnswers.ts, server/routes/appointments/create-and-edit/handlers/dateAndTime.test.ts, server/routes/appointments/create-and-edit/handlers/dateAndTime.ts, server/routes/appointments/create-and-edit/handlers/reviewPrisoners.test.ts, server/routes/appointments/create-and-edit/handlers/reviewPrisoners.ts, server/routes/appointments/create-and-edit/handlers/reviewPrisonersAlerts.test.ts, server/routes/appointments/create-and-edit/handlers/reviewPrisonersAlerts.ts, server/routes/appointments/create-and-edit/handlers/schedule.test.ts, server/routes/appointments/create-and-edit/handlers/schedule.ts, server/routes/appointments/create-and-edit/handlers/startJourney.test.ts, server/routes/appointments/create-and-edit/handlers/startJourney.ts, server/routes/appointments/index.ts, server/views/pages/appointments/appointment/copy.njk, server/views/pages/appointments/appointment/details.njk, server/views/pages/appointments/create-and-edit/date-and-time.njk, server/views/pages/appointments/create-and-edit/schedule.njk
After user select copy appointment this PR will allow user to:
- Update prisoners as normal
- Review any alerts as normal
- Enter a date for the new appointment, but not the times as they will be copied
- Review the schedule as normal
- Update anything from check answer as normal
There are follow up tasks to:
- filter out any prisoners who have left the prison
- chose to duplicate the whole series or not
- add metrics
=> SAA-1655: Initialise journey happy path

server/routes/appointments/create-and-edit/createRoutes.ts, server/routes/appointments/create-and-edit/editRoutes.ts, server/routes/appointments/create-and-edit/handlers/copySeries.test.ts, server/routes/appointments/create-and-edit/handlers/howToAddPrisoners.test.ts, server/routes/appointments/create-and-edit/handlers/howToAddPrisoners.ts, server/routes/appointments/create-and-edit/handlers/noAttendees.test.ts, server/routes/appointments/create-and-edit/handlers/noAttendees.ts, server/routes/appointments/create-and-edit/handlers/startJourney.test.ts, server/routes/appointments/create-and-edit/handlers/startJourney.ts, server/services/appointeeAttendeeService.test.ts, server/services/appointeeAttendeeService.ts, server/views/pages/appointments/create-and-edit/copy-series.njk, server/views/pages/appointments/create-and-edit/how-to-add-prisoners.njk, server/views/pages/appointments/create-and-edit/no-attendees.njk
When duplicating the appointment remove any existing attendees who are either permanently release or in another prison.
New "no attendees" view:
=> SAA-1655: Remove any unavailable attendees

server/@types/activitiesAPI/index.d.ts, server/routes/appointments/create-and-edit/handlers/checkAnswers.test.ts, server/routes/appointments/create-and-edit/handlers/checkAnswers.ts
Pass `originalAppointmentId` in create appointment request so API came add the id to the telemetry
=> SAA-1655: Add original appointment id to event metric

server/@types/activitiesAPI/index.d.ts, server/services/unlockListService.test.ts, server/services/unlockListService.ts
If the appointment repeats daily, the appointment will be shown on the ‘Unlock list’ for 2 days from the first cancelled appointment before being removed
If the appointment repeats every weekday, the appointment will be shown on the ‘Unlock list’  for 4 days from the first cancelled appointment before being removed
If the appointment repeats weekly, the appointment will be shown on the ‘Unlock list’ for 2 weeks from the first cancelled appointment before being removed
If the appointment repeats fortnightly, the appointment will be shown on the ‘Unlock list’ for 4 weeks from the first cancelled appointment before being removed
If the appointment repeats monthly, the appointment will be shown on the ‘Unlock list’ for 2 months from the first cancelled appointment before being removed
=> SAA-1143 apply cancelled appointments rules on the unlock list

integration_tests/e2e/appointments/createAppointment.cy.ts, integration_tests/e2e/appointments/createAppointmentBackLinks.cy.ts, integration_tests/e2e/appointments/createAppointmentCheckAnswers.cy.ts, integration_tests/e2e/appointments/createAppointmentCsvUploadValidation.cy.ts, integration_tests/e2e/appointments/createInCellAppointment.cy.ts, integration_tests/e2e/appointments/createRepeatAppointment.cy.ts, integration_tests/e2e/appointments/createRetrospectiveAppointment.cy.ts, integration_tests/e2e/appointments/duplicateAppointment.cy.ts, integration_tests/e2e/appointments/manageAppointment.cy.ts, integration_tests/fixtures/activitiesApi/getAppointmentSearchResults.json, integration_tests/fixtures/activitiesApi/getGroupAppointmentDetails.json, integration_tests/fixtures/prisonerSearchApi/postPrisonerNumbers-A1350DZ-A8644DY-A1351DZ.json, integration_tests/index.d.ts, integration_tests/pages/appointments/appointment/appointmentDetailsPage.ts, integration_tests/pages/appointments/appointment/appointmentsSearchResultsPage.ts, integration_tests/pages/appointments/appointment/copySummaryPage.ts, integration_tests/pages/appointments/appointmentsManagementPage.ts, integration_tests/pages/appointments/create-and-edit/copySeriesPage.ts, integration_tests/pages/appointments/create-and-edit/howToAddPrisonersPage.ts, integration_tests/pages/appointments/create-and-edit/noAttendeesPage.ts, integration_tests/pages/index.ts, integration_tests/support/commands.ts, server/services/appointeeAttendeeService.test.ts, server/services/appointeeAttendeeService.ts
- Add Cypress tests
- Ensure that that any prisoner not recognised by the search API from the original appointment is not copied to the new appointment
- Reduce boiler-plate in Cypress tests
=> SAA-1655: Add Cypress tests

server/routes/activities/record-attendance/handlers/attendanceList.test.ts, server/services/unlockListService.test.ts, server/utils/applyCancellationDisplayRule.test.ts, server/utils/applyCancellationDisplayRule.ts
Currently it excludes today, so for example if DAILY it should only show for 1 historic day (include the appointment day), not 2.
=> SAA-1143: change to cancellation display rules to also count the day of the appointment

server/utils/applyCancellationDisplayRule.test.ts
fix the cancellation rules tests where there is a date boundary failure for the monthly rule running on the 31st and the previous month does not have a 31st
=> SAA-1143: fix the cancellation rules tests where there is a date boundary failure

integration_tests/e2e/activities/attendance/multipleActivities.cy.ts, server/routes/activities/record-attendance/handlers/activities.test.ts, server/routes/activities/record-attendance/handlers/activities.ts, server/routes/activities/record-attendance/handlers/attendanceList.test.ts, server/routes/activities/record-attendance/handlers/attendanceList.ts, server/views/pages/activities/record-attendance/attendance-list-multiple.njk, server/views/pages/activities/record-attendance/attendance-list-single.njk, server/views/partials/formatSessions.njk
When marking attendance, if the user selects one single activity session then redirect to the view that shows only one activity / session such that the user can then print the attendance list or cancel the session
=> SAA-1737: Redirect to single activity session view if only one instances is selected for updating attendance

server/routes/appointments/video-link-booking/middleware/initialiseJourney.ts
This middleware was not wrapped in any kind of try-catch method. So if an error occurred during communication with the APIs it calls, the pod would just crash.
There are more examples of this issue across the codebase which all should be addressed, I propose this precedent for what I think the fix should be
=> Fix error handling of async middleware in book a video link journey

helm_deploy/values-dev.yaml, server/routes/activities/create-an-activity/handlers/sessionTimes.test.ts, server/routes/activities/create-an-activity/handlers/sessionTimes.ts, server/utils/helpers/activityTimeSlotMappers.test.ts, server/utils/helpers/activityTimeSlotMappers.ts, server/utils/helpers/applicableRegimeTimeUtil.ts, server/views/pages/activities/create-an-activity/session-times.njk
This allows the creation of custom times for an activity. It also switches on the functionality in Dev. NB. Validation is not covered yet.
=> SAA-1940: Select start end times session page

server/data/bookAVideoLinkApiClient.test.ts, server/data/bookAVideoLinkApiClient.ts, server/routes/appointments/video-link-booking/handlers/checkBooking.test.ts, server/routes/appointments/video-link-booking/handlers/checkBooking.ts, server/routes/appointments/video-link-booking/handlers/confirmation.test.ts, server/routes/appointments/video-link-booking/handlers/confirmation.ts, server/routes/appointments/video-link-booking/handlers/hearingDetails.test.ts, server/routes/appointments/video-link-booking/handlers/hearingDetails.ts, server/services/bookAVideoLinkService.test.ts, server/services/bookAVideoLinkService.ts, server/views/pages/appointments/video-link-booking/confirmation.njk
The following warning message is shown when creating a court video link booking if the court is disabled (i.e. BLVS not active for that court).
=> BAVL-301 show warning message on BVLS court booking confirmation page if court is disabled.

server/routes/activities/record-attendance/handlers/activities.test.ts, server/views/pages/activities/record-attendance/activities.njk
Also fixed a minor bug where the locations filter wasn't preserved when you navigate to the 'previous day'/'next day' on the table. (not sure if there's another ticket for this...)
=> SAA-1982 removed rogue locations ui filter element

package-lock.json, package.json, server/views/pages/activities/create-an-activity/check-answers.njk, server/views/pages/activities/daily-attendance-summary/cancelled-sessions.njk, server/views/pages/activities/manage-allocations/check-answers.njk, server/views/pages/activities/manage-allocations/exclusions.njk, server/views/pages/activities/record-attendance/activities.njk, server/views/pages/activities/record-attendance/attendance-list-single.njk, server/views/partials/attendance/activitiesTable.njk, server/views/partials/attendance/otherEvent.njk, server/views/partials/showLocation.njk
- Show non internal locations for clashing events in attendance list.
- Show selected week in exclusions when allocation bi-weekly activity
- Create a re-usable macro for showing location
=> SAA-2004: Fix location in attendances clashing events

server/routes/activities/change-of-circumstances/handlers/changeOfCircumstanceRoutes.ts, server/routes/activities/change-of-circumstances/handlers/changeOfCircumstancesRoutes.test.ts
The name was being reversed before going into a macro which reversed it again...
=> SAA-2033: Prisoner name reversal

package-lock.json, package.json
Fix for https://github.com/advisories/GHSA-pxg6-pf52-xh8x security issue in child dependency package as the 'csurf' package we use is deprecated/never going to be updated. Discussion for its replacement is ongoing.
=> override cookie child package dependency

integration_tests/e2e/activities/allocations/allocateToActivity.cy.ts, integration_tests/e2e/activities/allocations/deallocateFromActivity.cy.ts, integration_tests/fixtures/activitiesApi/getAllocations.json, server/views/partials/activities/allocation-dashboard/nonAssociationsHtml.njk
We should send the user to the new non-associations page with a link in the correct column if the endpoint we call returns a null response (if non-associations API errors). The user should be able to get the information they need from the new non-associations page as that endpoint is working okay in the non-associations API.
=> SAA-1988: Deal with null response from api for non-associations

server/routes/activities/daily-attendance-summary/handlers/applyFilters.test.ts, server/routes/activities/daily-attendance-summary/handlers/applyFilters.ts, server/views/partials/activities/absencesCheckboxes.njk
If user selects some but not all categories in attendance summary view:
then ensure that the Absences and Pay checkboxes are all selected in the absences summary view:
=> SAA-2212: Fix checkboxes in absences view when moving from summary attendances view

package-lock.json, package.json
Having to override versions of package dependencies to resolve https://github.com/advisories/GHSA-rhx6-c78j-4q9w and https://github.com/advisories/GHSA-3xgq-45jj-v275
Updating path-to-regexp without overriding would requires express v5 upgrade (jira: https://dsdmoj.atlassian.net/browse/SAA-2232)
Updating cross-spawn without overriding would require eslint v9 upgrade (jira: https://dsdmoj.atlassian.net/browse/SAA-2235)
=> Resolve dependency package CVEs

package.json, renovate.json
There's jira tickets to resolve these upgrades properly, this is just a temp solution to avoid breaking changes every time it tries to create a non major dependency update PR.
=> add packages to renovate ignore config to avoid breaking changes in non major upgrades

server/views/pages/appointments/attendance/summaries-multi-select.njk
Add a link to allow users to go to the appointment attendance summary view.
=> SAA-2197: Add summary link to appointments attendance summary view

server/config.ts
removed product id variable as it's currently not required or relavent
=> fix deployment error

server/routes/activities/change-of-circumstances/handlers/selectPeriodForChanges.ts, server/routes/activities/daily-attendance-summary/handlers/notAttendedSelectDate.test.ts, server/routes/activities/daily-attendance-summary/handlers/notAttendedSelectDate.ts, server/routes/activities/daily-attendance-summary/handlers/selectPeriod.ts, server/routes/activities/record-attendance/handlers/selectPeriod.test.ts, server/routes/activities/record-attendance/handlers/selectPeriod.ts, server/routes/activities/unlock-list/handlers/selectDateAndLocation.ts, server/utils/utils.ts, server/views/pages/activities/change-of-circumstances/select-period.njk, server/views/pages/activities/record-attendance/activities.njk, server/views/pages/activities/record-attendance/select-period.njk
Fixes the back link on the 'find an activity to record...' page to go back to the select-period page, and make sure it renders the datePresetOption and the sessions that were previously selected.
Includes a refactor to amalgamate related enums and functions to ensure that the datePresetOptions are pre-selected on various pages.
=> SAA-2290: Back link fix and refactor

server/routes/appointments/attendance/handlers/attendees.test.ts, server/routes/appointments/attendance/handlers/attendees.ts, server/routes/appointments/attendance/handlers/editAttendance.test.ts, server/routes/appointments/attendance/handlers/editAttendance.ts, server/views/pages/appointments/attendance/attendees.njk, server/views/pages/appointments/attendance/summaries-multi-select.njk
[SAA-2294]: https://dsdmoj.atlassian.net/browse/SAA-2294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SAA-2295]: https://dsdmoj.atlassian.net/browse/SAA-2295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SAA-2296]: https://dsdmoj.atlassian.net/browse/SAA-2296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SAA-2297]: https://dsdmoj.atlassian.net/browse/SAA-2297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SAA-2298]: https://dsdmoj.atlassian.net/browse/SAA-2298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SAA-2299]: …
=> SAA-2197: Fix mark appointment attendances UI issues

.circleci/config.yml
Created new [activities-and-appointments-alerts-security](https://moj.enterprise.slack.com/archives/C08BVFF9TFG) channel for security alerts
Moved release alerts to dev channel as per guidance https://tech-docs.hmpps.service.justice.gov.uk/creating-new-services/prerequisites/
=> SAA-2327 update circle ci alerts channels

server/views/pages/appointments/video-link-booking/probation/booking-cancelled.njk, server/views/pages/appointments/video-link-booking/probation/confirmation.njk
Small textual change to message shown to prison users if choose a probation team that is not able to use BVLS directly.  
This is to allow it to be more generic e.g. if they choose 'Team not listed' which is available as probation team choice.
=> BAVL-696 make the confirmation text for probation teams not yet using BVLS to be team agnostic to allow for 'Team not listed'.

server/views/pages/appointments/video-link-booking/court/confirm-cancel.njk, server/views/pages/appointments/video-link-booking/probation/confirm-cancel.njk
This change removes the prisoner name from the video link page title(s) but still includes in the header(s).
I have made this change to prevent the name bing included in any page analytics.
=> BAVL-792 removing prisoner names from the video link page titles but still including in the headers.

integration_tests/e2e/activities/suspensions.cy.ts, server/views/pages/appointments/video-link-booking/court/check-booking.njk, server/views/pages/appointments/video-link-booking/court/details.njk, server/views/pages/appointments/video-link-booking/probation/check-booking.njk, server/views/pages/appointments/video-link-booking/probation/details.njk
Content sweep for the BVLS court and probation appointment journeys to provide a consistent look for the staff and prisoner note.
=> BAVL-899 content sweep changes for the BVLS court and probation appointment journeys.

server/routes/appointments/video-link-booking/court/handlers/extraInformation.test.ts, server/routes/appointments/video-link-booking/court/handlers/extraInformation.ts, server/routes/appointments/video-link-booking/probation/handlers/extraInformation.test.ts, server/routes/appointments/video-link-booking/probation/handlers/extraInformation.ts, server/views/pages/appointments/video-link-booking/court/extra-information.njk, server/views/pages/appointments/video-link-booking/probation/extra-information.njk
Small error message tidy up for consistency across services where BVLS bookings can be created.
**Court journey:**
**Probation journey:**
=> BAVL-919 small error message change to be consistent with BVLS and DPS services for notes.

integration_tests/e2e/activities/unlockList.cy.ts, integration_tests/pages/unlockAndMovements/unlock/plannedEventsPage.ts, server/routes/activities/unlock-list/handlers/plannedEvents.test.ts, server/routes/activities/unlock-list/handlers/plannedEvents.ts, server/services/unlockListService.test.ts, server/services/unlockListService.ts
If the user uses the activity category filter, then **only** activities are shown on the page
If the user doesn't engage with the activity category filter, all event types are shown (filtered as before)
=> SAA-3504: Unlock list activity cat filter change

server/views/pages/activities/create-an-activity/edit-pay.njk
Pay rate history with migration changes
Do not show change option for the pay rate which has an existing change
=> SAA-1911: Changes based on dev validation

server/routes/activities/manage-allocations/createRoutes.ts, server/routes/activities/manage-allocations/editRoutes.ts, server/routes/activities/manage-allocations/excludeRoutes.ts, server/routes/activities/manage-allocations/removeRoutes.ts
Remove calls to [setUpJourneyData](https://github.com/ministryofjustice/hmpps-activities-management/blob/1514471978cb0e2f09c42b4868fcfbca9820b2b7/server/middleware/setUpJourneyData.ts) in routes as they are called in [index.ts](https://github.com/ministryofjustice/hmpps-activities-management/blob/3d4e9e2b486822969eddb10ab4d55c7636a64e0b/server/routes/activities/manage-allocations/index.ts) anyway and this meant journey data was being saved twice.
=> SAA-3622: Remove extraneous calls to setup journey data for remove allocation

integration_tests/e2e/activities/movementList.cy.ts, integration_tests/fixtures/activitiesApi/getScheduledEventLocations.json, integration_tests/pages/unlockAndMovements/abstractEventsPage.ts, server/@types/activities.ts, server/routes/activities/movement-list/handlers/applyFilters.test.ts, server/routes/activities/movement-list/handlers/applyFilters.ts, server/routes/activities/movement-list/handlers/locationEvents.ts, server/routes/activities/movement-list/journey.ts, server/views/pages/activities/movement-list/location-events.njk
Added show cancelled events filter to the movement list and added cypress tests to check filter behaviour
=> SAA-3429: Movement list cancelled events filter
